/*
 * sound_data.c - BGM data for NgpCraft_base_template
 *
 * Part of NgpCraft_base_template (MIT License)
 *
 * Hybrid export layout:
 *   - sound_sample.c             : note table + BGM streams
 *   - sound_sample_instruments.c : instrument presets (included by sounds.c)
 */

#include "sound_data.h"

/* BGM streams + NOTE_TABLE — generated by NGPC Sound Creator */
#include "sound_sample.c"

/* SFX count (no SFX in this demo) */
const u8 SFX_COUNT = 0;
