/*
 * sound_data.h - Sound asset declarations (BGM streams, SFX presets, note tables)
 *
 * Part of NgpCraft_base_template (MIT License)
 *
 * This header declares all sound data arrays.
 * The actual data lives in .c files in this folder (generated by tools
 * or hand-authored). Game code includes this header to access the data.
 *
 * Typical workflow (template default):
 *   1. NGPC Sound Creator exports a hybrid pair:
 *      - sound_sample.c
 *      - sound_sample_instruments.c
 *   2. Drop both files into this sound/ folder
 *   3. sound_data.c includes sound_sample.c
 *   4. src/audio/sounds.c includes sound_sample_instruments.c
 *
 * If you rename the exported files, update those #include lines.
 */

#ifndef SOUND_DATA_H
#define SOUND_DATA_H

#include "ngpc_types.h"

/* ---- Note table (frequency dividers for note indices 1..50) ---- */
extern const u8 NOTE_TABLE[];

/* ---- BGM streams (one per voice) ---- */
extern const u8 BGM_CH0[];     /* Tone voice 0 */
extern const u8 BGM_CH1[];     /* Tone voice 1 */
extern const u8 BGM_CH2[];     /* Tone voice 2 */
extern const u8 BGM_CHN[];     /* Noise voice  */

/* ---- BGM loop offsets (byte offset into each stream) ---- */
extern const u16 BGM_CH0_LOOP;
extern const u16 BGM_CH1_LOOP;
extern const u16 BGM_CH2_LOOP;
extern const u16 BGM_CHN_LOOP;

/* ---- SFX preset count ---- */
extern const u8 SFX_COUNT;

#endif /* SOUND_DATA_H */
