/* Auto-generated by ngpc_font_export.py — DO NOT EDIT
 * Source : Ahchay_alphabet.png
 *
 * Usage:
 *   #include "GraphX/ahchay_font.h"
 *   // In init, instead of ngpc_load_sysfont():
 *   ahchay_font_load();
 *   // ngpc_text_print() then works with the custom font.
 */
#ifndef NGPC_AHCHAY_FONT_H
#define NGPC_AHCHAY_FONT_H

#include "ngpc_types.h"
#include "../gfx/ngpc_gfx.h"

/* VRAM tile slot for the first character (space, ASCII 32).
 * tile_slot = ascii_code  — identical mapping to the BIOS system font. */
#define NGPC_FONT_TILE_BASE   32u
/* Total number of tiles in this font (ASCII 32–127). */
#define NGPC_FONT_TILE_COUNT  96u

extern const u16 NGP_FAR ahchay_font_tiles[NGPC_FONT_TILE_COUNT * 8u];

/* Load the custom font into Character RAM.
 * Call once at startup, replaces ngpc_load_sysfont().
 * After this call ngpc_text_print() uses the custom font. */
#define ahchay_font_load() ngpc_gfx_load_tiles_at(ahchay_font_tiles, NGPC_FONT_TILE_COUNT * 8u, NGPC_FONT_TILE_BASE)


/* Font palette extracted from PNG source */
#define AHCHAY_FONT_PAL_C0  RGB(0,0,0)
#define AHCHAY_FONT_PAL_C1  RGB(15,15,15)
#define AHCHAY_FONT_PAL_C2  RGB(0,0,0)
#define AHCHAY_FONT_PAL_C3  RGB(0,0,0)
#define ahchay_font_set_palette(plane, pal_slot) ngpc_gfx_set_palette(plane, (u8)(pal_slot), AHCHAY_FONT_PAL_C0, AHCHAY_FONT_PAL_C1, AHCHAY_FONT_PAL_C2, AHCHAY_FONT_PAL_C3)
#endif /* NGPC_AHCHAY_FONT_H */
