/* Generated by tools/export_caisse.py - do not edit */
#ifndef CAISSE_TILES_H
#define CAISSE_TILES_H

#include "ngpc_types.h"

/* 4 tiles NGPC 2bpp (TL TR BL BR) = 32 u16. */
extern const u16 NGP_FAR caisse_tiles[32];

/* Palette 4 couleurs : C0 transp, C1 marron fonce, C2 marron clair, C3 unused.
 * Identique a hent_palettes (a charger une seule fois en SCR2 slot dedie). */
extern const u16 NGP_FAR caisse_palette[4];

#endif /* CAISSE_TILES_H */
