/* Generated by ngpc_sprite_export.py - do not edit */

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

/* Runtime note: call ngpc_mspr_draw(..., SPR_FRONT|optional flips). */

const u16 coffre_tiles_count = 32u;
const u16 coffre_tiles[] = {
    0x0AAA, 0x2555, 0x9A6A, 0x9555, 0x9556, 0xAAAA, 0x966F, 0x956F, 0xAAA0, 0x5558, 0xAAA6, 0x5556,
    0x9556, 0xAAAA, 0xF996, 0xF996, 0x965A, 0x9659, 0x9659, 0x9659, 0x9659, 0x9559, 0x9659, 0xAAAA,
    0xA556, 0x6596, 0x6596, 0x5596, 0x6556, 0x6596, 0x6596, 0xAAAA
};

const u8 coffre_palette_count = 1u;
const u16 coffre_palettes[] = {
    0x0000, 0x0147, 0x0000, 0x0888
};

const u8 coffre_pal_base = 11u;

const u16 coffre_tile_base = 226u;

const NgpcMetasprite coffre_frame_0 = {
    4u, 16u, 16u,
    {
        { 0, 0, 226, 11, 0 },
        { 8, 0, 227, 11, 0 },
        { 0, 8, 228, 11, 0 },
        { 8, 8, 229, 11, 0 }
    }
};

const MsprAnimFrame coffre_anim[] = {
    { &coffre_frame_0, 6 }
};

const u8 coffre_anim_count = 1u;
