/* Generated by ngpc_sprite_export.py - do not edit */

#ifndef COFFRE_MSPR_H
#define COFFRE_MSPR_H

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

extern const u16 coffre_tiles_count;
extern const u16 NGP_FAR coffre_tiles[];

extern const u8 coffre_palette_count;
extern const u16 NGP_FAR coffre_palettes[];
extern const u8 coffre_pal_base;
extern const u16 coffre_tile_base;

extern const NgpcMetasprite coffre_frame_0;

extern const MsprAnimFrame coffre_anim[];
extern const u8 coffre_anim_count;

#endif /* COFFRE_MSPR_H */
