/* Generated by tools/export_door_lock.py - do not edit */
#ifndef DECLENCHEUR_TILES_H
#define DECLENCHEUR_TILES_H

#include "ngpc_types.h"

/* 4 tiles 8x8 NGPC (TL TR BL BR) = 32 u16. */
extern const u16 NGP_FAR declencheur_tiles[32];

/* Palette 4 couleurs SCR1 : C0 transp, C1 noir, C2 gris fonce, C3 gris clair. */
extern const u16 NGP_FAR declencheur_palette[4];

#endif /* DECLENCHEUR_TILES_H */
