/* Generated by tools/export_door_lock.py - do not edit */
#ifndef DOOR_SHEET_TILES_H
#define DOOR_SHEET_TILES_H

#include "ngpc_types.h"

/* 4 frames x 4 tiles 8x8 = 16 tiles NGPC = 128 u16.
 * Frame 0 = porte fermee, frame 3 = juste avant fully open
 * (la frame fully open est la porte existante TILE_U_DOOR_N).
 * Layout : pour frame F, tile base = frame_base + F * 4.
 *
 * _ns = orientation source (verticale, pour exits N/S).
 *       Pour S : vflip HW.
 * _we = rotation 90 deg CCW (horizontale, pour exits W/E).
 *       Pour E : hflip HW. */
extern const u16 NGP_FAR door_sheet_tiles_ns[128];
extern const u16 NGP_FAR door_sheet_tiles_we[128];

/* Palette 4 couleurs SCR1 : C0 transp, C1 noir, C2 stone, C3 wood. */
extern const u16 NGP_FAR door_sheet_palette[4];

#endif /* DOOR_SHEET_TILES_H */
