/* Generated by ngpc_sprite_export.py - do not edit */

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

/* Runtime note: call ngpc_mspr_draw(..., SPR_FRONT|optional flips). */

const u16 effect_attaque_crit_tiles_count = 24u;
const u16 effect_attaque_crit_tiles[] = {
    0x0000, 0x0000, 0x0000, 0x0000, 0x0001, 0x0015, 0x005A, 0x0069, 0x0005, 0x0159, 0x05A4, 0x1640,
    0x6900, 0xA400, 0x5000, 0x4000, 0x0065, 0x0194, 0x0190, 0x0650, 0x0640, 0x1900, 0x1400, 0x1000
};

const u8 effect_attaque_crit_palette_count = 1u;
const u16 effect_attaque_crit_palettes[] = {
    0x0000, 0x00AF, 0x00DF, 0x0000
};

const u8 effect_attaque_crit_pal_base = 5u;

const u16 effect_attaque_crit_tile_base = 168u;

const NgpcMetasprite effect_attaque_crit_frame_0 = {
    3u, 16u, 16u,
    {
        { 0, 0, 168, 5, 0 },
        { 8, 0, 169, 5, 0 },
        { 0, 8, 170, 5, 0 }
    }
};

const MsprAnimFrame effect_attaque_crit_anim[] = {
    { &effect_attaque_crit_frame_0, 6 }
};

const u8 effect_attaque_crit_anim_count = 1u;
