/* Generated by ngpc_sprite_export.py - do not edit */

#ifndef EFFECT_ATTAQUE_MSPR_H
#define EFFECT_ATTAQUE_MSPR_H

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

extern const u16 effect_attaque_tiles_count;
extern const u16 NGP_FAR effect_attaque_tiles[];

extern const u8 effect_attaque_palette_count;
extern const u16 NGP_FAR effect_attaque_palettes[];
extern const u8 effect_attaque_pal_base;
extern const u16 effect_attaque_tile_base;

extern const NgpcMetasprite effect_attaque_frame_0;

extern const MsprAnimFrame effect_attaque_anim[];
extern const u8 effect_attaque_anim_count;

#endif /* EFFECT_ATTAQUE_MSPR_H */
