/* Generated by ngpc_sprite_export.py - do not edit */

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

/* Runtime note: call ngpc_mspr_draw(..., SPR_FRONT|optional flips). */

const u16 effect_attaque_tiles_count = 24u;
const u16 effect_attaque_tiles[] = {
    0x0000, 0x0000, 0x0000, 0x0000, 0x0001, 0x0015, 0x005F, 0x007D, 0x0005, 0x0159, 0x05A4, 0x1640,
    0x6900, 0xF400, 0x5000, 0x4000, 0x0075, 0x01D4, 0x01D0, 0x0650, 0x0640, 0x1900, 0x1400, 0x1000
};

const u8 effect_attaque_palette_count = 1u;
const u16 effect_attaque_palettes[] = {
    0x0000, 0x0C60, 0x0B74, 0x0B97
};

const u8 effect_attaque_pal_base = 4u;

const u16 effect_attaque_tile_base = 164u;

const NgpcMetasprite effect_attaque_frame_0 = {
    3u, 16u, 16u,
    {
        { 0, 0, 164, 4, 0 },
        { 8, 0, 165, 4, 0 },
        { 0, 8, 166, 4, 0 }
    }
};

const MsprAnimFrame effect_attaque_anim[] = {
    { &effect_attaque_frame_0, 4 }
};

const u8 effect_attaque_anim_count = 1u;
