/* Generated by ngpc_sprite_export.py - do not edit */

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

/* Runtime note: call ngpc_mspr_draw(..., SPR_FRONT|optional flips). */

const u16 flamme_tiles_count = 64u;
const u16 flamme_tiles[] = {
    0x0000, 0x00A2, 0x0020, 0x0004, 0x002A, 0x0099, 0x0155, 0x0695, 0x0000, 0x8000, 0x8000, 0x1800,
    0x6000, 0x4000, 0xA400, 0x6400, 0x0557, 0x025F, 0x097F, 0x15EF, 0x17AB, 0x25FF, 0x0279, 0x0016,
    0x5900, 0xD660, 0xFD80, 0xEFA0, 0xAB58, 0xFF60, 0xB500, 0x5800, 0x0000, 0x0000, 0x00A2, 0x0020,
    0x0004, 0x002A, 0x0099, 0x0555, 0x0000, 0x0000, 0x8000, 0x8000, 0x1800, 0x6000, 0x4000, 0xA400,
    0x1557, 0x0A5F, 0x257F, 0x55EF, 0x5FAB, 0x95FF, 0x0A79, 0x0016, 0x5940, 0xD698, 0xFD60, 0xEFE8,
    0xABD6, 0xFFD8, 0xB540, 0x5800
};

const u8 flamme_palette_count = 1u;
const u16 flamme_palettes[] = {
    0x0000, 0x07B6, 0x0563, 0x08E9
};

const u8 flamme_pal_base = 9u;

const u16 flamme_tile_base = 184u;

const NgpcMetasprite flamme_frame_0 = {
    4u, 16u, 16u,
    {
        { 0, 0, 184, 9, 0 },
        { 8, 0, 185, 9, 0 },
        { 0, 8, 186, 9, 0 },
        { 8, 8, 187, 9, 0 }
    }
};

const NgpcMetasprite flamme_frame_1 = {
    4u, 16u, 16u,
    {
        { 0, 0, 188, 9, 0 },
        { 8, 0, 189, 9, 0 },
        { 0, 8, 190, 9, 0 },
        { 8, 8, 191, 9, 0 }
    }
};

const MsprAnimFrame flamme_anim[] = {
    { &flamme_frame_0, 6 },
    { &flamme_frame_1, 6 }
};

const u8 flamme_anim_count = 2u;
