/* Generated by ngpc_sprite_export.py - do not edit */

#ifndef FLAMME_MSPR_H
#define FLAMME_MSPR_H

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

extern const u16 flamme_tiles_count;
extern const u16 NGP_FAR flamme_tiles[];

extern const u8 flamme_palette_count;
extern const u16 NGP_FAR flamme_palettes[];
extern const u8 flamme_pal_base;
extern const u16 flamme_tile_base;

extern const NgpcMetasprite flamme_frame_0;
extern const NgpcMetasprite flamme_frame_1;

extern const MsprAnimFrame flamme_anim[];
extern const u8 flamme_anim_count;

#endif /* FLAMME_MSPR_H */
