/* Generated by ngpc_tilemap.py - do not edit */

#ifndef GAME_OVER_SCREEN_TILEMAP_H
#define GAME_OVER_SCREEN_TILEMAP_H

#include "ngpc_types.h"

extern const u16 game_over_screen_map_w;
extern const u16 game_over_screen_map_h;
extern const u16 game_over_screen_map_len;

extern const u8 game_over_screen_palette_count;
extern const u16 NGP_FAR game_over_screen_palettes[];

extern const u16 game_over_screen_tiles_count;
extern const u16 NGP_FAR game_over_screen_tiles[];

extern const u16 NGP_FAR game_over_screen_map_tiles[];
extern const u8 NGP_FAR game_over_screen_map_pals[];

#endif /* GAME_OVER_SCREEN_TILEMAP_H */
