/* Generated by ngpc_sprite_export.py - do not edit */

#ifndef HENT_MSPR_H
#define HENT_MSPR_H

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

extern const u16 hent_tiles_count;
extern const u16 NGP_FAR hent_tiles[];

extern const u8 hent_palette_count;
extern const u16 NGP_FAR hent_palettes[];
extern const u8 hent_pal_base;
extern const u16 hent_tile_base;

extern const NgpcMetasprite hent_frame_0;
extern const NgpcMetasprite hent_frame_1;

extern const MsprAnimFrame hent_anim[];
extern const u8 hent_anim_count;

#endif /* HENT_MSPR_H */
