/* Generated by ngpc_sprite_export.py - do not edit */

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

/* Runtime note: call ngpc_mspr_draw(..., SPR_FRONT|optional flips). */

const u16 hent_tiles_count = 48u;
const u16 hent_tiles[] = {
    0x0000, 0x0010, 0x0015, 0x0C05, 0x3816, 0x381A, 0x381F, 0x3815, 0x5000, 0x5040, 0x5540, 0xA500,
    0xA940, 0x5A40, 0xAF40, 0xA540, 0x380A, 0x3815, 0x1657, 0x1541, 0x0802, 0x080A, 0x0829, 0x0854,
    0x5A00, 0x55A0, 0xFD68, 0xF41A, 0xF806, 0x5A8A, 0x01A0, 0x0054, 0x0000, 0x0010, 0x0C15, 0x3805,
    0x3816, 0x381A, 0x381F, 0x3815, 0x380A, 0x1655, 0x1557, 0x0801, 0x0802, 0x080A, 0x0829, 0x0054
};

const u8 hent_palette_count = 1u;
const u16 hent_palettes[] = {
    0x0000, 0x0135, 0x0269, 0x0000
};

const u8 hent_pal_base = 10u;

const u16 hent_tile_base = 196u;

const NgpcMetasprite hent_frame_0 = {
    4u, 16u, 16u,
    {
        { 0, 0, 196, 10, 0 },
        { 8, 0, 197, 10, 0 },
        { 0, 8, 198, 10, 0 },
        { 8, 8, 199, 10, 0 }
    }
};

const NgpcMetasprite hent_frame_1 = {
    4u, 16u, 16u,
    {
        { 0, 0, 200, 10, 0 },
        { 8, 0, 197, 10, 0 },
        { 0, 8, 201, 10, 0 },
        { 8, 8, 199, 10, 0 }
    }
};

const MsprAnimFrame hent_anim[] = {
    { &hent_frame_0, 6 },
    { &hent_frame_1, 6 }
};

const u8 hent_anim_count = 2u;
