/* Generated by ngpc_tilemap.py - do not edit */

#ifndef HUD_BG_TILEMAP_H
#define HUD_BG_TILEMAP_H

#include "ngpc_types.h"

extern const u16 hud_bg_map_w;
extern const u16 hud_bg_map_h;
extern const u16 hud_bg_map_len;

extern const u8 hud_bg_palette_count;
extern const u16 NGP_FAR hud_bg_palettes[];

extern const u16 hud_bg_tiles_count;
extern const u16 NGP_FAR hud_bg_tiles[];

extern const u16 NGP_FAR hud_bg_map_tiles[];
extern const u8 NGP_FAR hud_bg_map_pals[];

#endif /* HUD_BG_TILEMAP_H */
