/* Generated by ngpc_sprite_export.py - do not edit */

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

/* Runtime note: call ngpc_mspr_draw(..., SPR_FRONT|optional flips). */

const u16 hud_tiles_count = 72u;
const u16 hud_tiles[] = {
    0x9AAB, 0xD6BD, 0x55D5, 0x5555, 0x5555, 0x5555, 0x5555, 0x5555, 0xAAA9, 0x7AAD, 0x57F5, 0x5555,
    0x5555, 0x5555, 0x5555, 0x5555, 0x6A6A, 0x5B5B, 0x5D5D, 0x5555, 0x5555, 0x5555, 0x5555, 0x5555,
    0x6AAF, 0xBF55, 0xD555, 0x5555, 0x5555, 0x5555, 0x5555, 0x5555, 0x5555, 0x5555, 0x5555, 0x5555,
    0x5555, 0x5555, 0x5555, 0x5555, 0x5555, 0x556A, 0x557F, 0x56FF, 0x5FEA, 0x5FEA, 0x5F95, 0x56D5,
    0x5555, 0xAA55, 0xEA95, 0xEBE5, 0xEAE9, 0xEBA9, 0x7EAA, 0x6AAA, 0x5BD5, 0x5FA5, 0x75AB, 0x75AF,
    0x657E, 0x5FAB, 0x5EE7, 0x5AE6, 0x6EAA, 0x7EAA, 0xFEAA, 0xEAA9, 0xAAA5, 0x5555, 0x5555, 0x5555
};

const u8 hud_palette_count = 1u;
const u16 hud_palettes[] = {
    0x0000, 0x0000, 0x0678, 0x08AB
};

const u8 hud_pal_base = 8u;

const u16 hud_tile_base = 400u;

const NgpcMetasprite hud_frame_0 = {
    10u, 40u, 16u,
    {
        { 0, 0, 400, 8, 0 },
        { 8, 0, 401, 8, 0 },
        { 16, 0, 402, 8, 0 },
        { 24, 0, 400, 8, 0 },
        { 32, 0, 403, 8, 0 },
        { 0, 8, 404, 8, 0 },
        { 8, 8, 404, 8, 0 },
        { 16, 8, 404, 8, 0 },
        { 24, 8, 404, 8, 0 },
        { 32, 8, 404, 8, 0 }
    }
};

const NgpcMetasprite hud_frame_1 = {
    10u, 40u, 16u,
    {
        { 0, 0, 401, 8, 0 },
        { 8, 0, 402, 8, 0 },
        { 16, 0, 400, 8, 0 },
        { 24, 0, 403, 8, 0 },
        { 32, 0, 402, 8, 0 },
        { 0, 8, 404, 8, 0 },
        { 8, 8, 404, 8, 0 },
        { 16, 8, 404, 8, 0 },
        { 24, 8, 404, 8, 0 },
        { 32, 8, 404, 8, 0 }
    }
};

const NgpcMetasprite hud_frame_2 = {
    10u, 40u, 16u,
    {
        { 0, 0, 401, 8, 0 },
        { 8, 0, 400, 8, 0 },
        { 16, 0, 403, 8, 0 },
        { 24, 0, 402, 8, 0 },
        { 32, 0, 401, 8, 0 },
        { 0, 8, 404, 8, 0 },
        { 8, 8, 404, 8, 0 },
        { 16, 8, 404, 8, 0 },
        { 24, 8, 404, 8, 0 },
        { 32, 8, 404, 8, 0 }
    }
};

const NgpcMetasprite hud_frame_3 = {
    10u, 40u, 16u,
    {
        { 0, 0, 402, 8, 0 },
        { 8, 0, 400, 8, 0 },
        { 16, 0, 403, 8, 0 },
        { 24, 0, 405, 8, 0 },
        { 32, 0, 406, 8, 0 },
        { 0, 8, 404, 8, 0 },
        { 8, 8, 404, 8, 0 },
        { 16, 8, 404, 8, 0 },
        { 24, 8, 407, 8, 0 },
        { 32, 8, 408, 8, 0 }
    }
};

const MsprAnimFrame hud_anim[] = {
    { &hud_frame_0, 6 },
    { &hud_frame_1, 6 },
    { &hud_frame_2, 6 },
    { &hud_frame_3, 6 }
};

const u8 hud_anim_count = 4u;
