/* Generated by ngpc_sprite_export.py - do not edit */

#ifndef HUD_MSPR_H
#define HUD_MSPR_H

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

extern const u16 hud_tiles_count;
extern const u16 NGP_FAR hud_tiles[];

extern const u8 hud_palette_count;
extern const u16 NGP_FAR hud_palettes[];
extern const u8 hud_pal_base;
extern const u16 hud_tile_base;

extern const NgpcMetasprite hud_frame_0;
extern const NgpcMetasprite hud_frame_1;
extern const NgpcMetasprite hud_frame_2;
extern const NgpcMetasprite hud_frame_3;

extern const MsprAnimFrame hud_anim[];
extern const u8 hud_anim_count;

#endif /* HUD_MSPR_H */
