/* Generated by ngpc_tilemap.py - do not edit */

#ifndef INTRO_NGPC_CRAFT_PNG_TILEMAP_H
#define INTRO_NGPC_CRAFT_PNG_TILEMAP_H

#include "ngpc_types.h"

extern const u8 intro_ngpc_craft_png_map_w;
extern const u8 intro_ngpc_craft_png_map_h;
extern const u16 intro_ngpc_craft_png_map_len;

extern const u8 intro_ngpc_craft_png_palette_count;
extern const u16 intro_ngpc_craft_png_palettes[];

extern const u16 intro_ngpc_craft_png_tiles_count;
extern const u16 intro_ngpc_craft_png_tiles[];

extern const u16 intro_ngpc_craft_png_map_tiles[];
extern const u8 intro_ngpc_craft_png_map_pals[];

#endif /* INTRO_NGPC_CRAFT_PNG_TILEMAP_H */
