/* Generated by ngpc_tilemap.py - do not edit */

#ifndef INVENTAIRE_TILEMAP_H
#define INVENTAIRE_TILEMAP_H

#include "ngpc_types.h"

extern const u16 inventaire_map_w;
extern const u16 inventaire_map_h;
extern const u16 inventaire_map_len;

extern const u8 inventaire_palette_count;
extern const u16 NGP_FAR inventaire_palettes[];

extern const u16 inventaire_tiles_count;
extern const u16 NGP_FAR inventaire_tiles[];

extern const u16 NGP_FAR inventaire_map_tiles[];
extern const u8 NGP_FAR inventaire_map_pals[];

#endif /* INVENTAIRE_TILEMAP_H */
