/* Generated by ngpc_sprite_export.py - do not edit */

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

/* Runtime note: call ngpc_mspr_draw(..., SPR_FRONT|optional flips). */

const u16 inventaire_selector_item_tiles_count = 64u;
const u16 inventaire_selector_item_tiles[] = {
    0x0155, 0x06AA, 0x1800, 0x6000, 0x6000, 0x6000, 0x6000, 0x6000, 0x5555, 0xAAAA, 0x0000, 0x0000,
    0x0000, 0x0000, 0x0000, 0x0000, 0x5540, 0xAA90, 0x0024, 0x0009, 0x0009, 0x0009, 0x0009, 0x0009,
    0x6000, 0x6000, 0x6000, 0x6000, 0x6000, 0x6000, 0x6000, 0x6000, 0x0009, 0x0009, 0x0009, 0x0009,
    0x0009, 0x0009, 0x0009, 0x0009, 0x6000, 0x6000, 0x6000, 0x6000, 0x6000, 0x1800, 0x06AA, 0x0155,
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0xAAAA, 0x5555, 0x0009, 0x0009, 0x0009, 0x0009,
    0x0009, 0x0024, 0xAA90, 0x5540
};

const u8 inventaire_selector_item_palette_count = 1u;
const u16 inventaire_selector_item_palettes[] = {
    0x0000, 0x0000, 0x03EF, 0x0000
};

const u8 inventaire_selector_item_pal_base = 11u;

const u16 inventaire_selector_item_tile_base = 210u;

const NgpcMetasprite inventaire_selector_item_frame_0 = {
    12u, 32u, 32u,
    {
        { 0, 0, 210, 11, 0 },
        { 8, 0, 211, 11, 0 },
        { 16, 0, 211, 11, 0 },
        { 24, 0, 212, 11, 0 },
        { 0, 8, 213, 11, 0 },
        { 24, 8, 214, 11, 0 },
        { 0, 16, 213, 11, 0 },
        { 24, 16, 214, 11, 0 },
        { 0, 24, 215, 11, 0 },
        { 8, 24, 216, 11, 0 },
        { 16, 24, 216, 11, 0 },
        { 24, 24, 217, 11, 0 }
    }
};

const MsprAnimFrame inventaire_selector_item_anim[] = {
    { &inventaire_selector_item_frame_0, 6 }
};

const u8 inventaire_selector_item_anim_count = 1u;
