/* Generated by ngpc_sprite_export.py - do not edit */

#ifndef INVENTAIRE_SELECTOR_ITEM_MSPR_H
#define INVENTAIRE_SELECTOR_ITEM_MSPR_H

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

extern const u16 inventaire_selector_item_tiles_count;
extern const u16 NGP_FAR inventaire_selector_item_tiles[];

extern const u8 inventaire_selector_item_palette_count;
extern const u16 NGP_FAR inventaire_selector_item_palettes[];
extern const u8 inventaire_selector_item_pal_base;
extern const u16 inventaire_selector_item_tile_base;

extern const NgpcMetasprite inventaire_selector_item_frame_0;

extern const MsprAnimFrame inventaire_selector_item_anim[];
extern const u8 inventaire_selector_item_anim_count;

#endif /* INVENTAIRE_SELECTOR_ITEM_MSPR_H */
