/* Generated by ngpc_sprite_export.py - do not edit */

#ifndef ITEM_POTION_MSPR_H
#define ITEM_POTION_MSPR_H

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

extern const u16 item_potion_tiles_count;
extern const u16 NGP_FAR item_potion_tiles[];

extern const u8 item_potion_palette_count;
extern const u16 NGP_FAR item_potion_palettes[];
extern const u8 item_potion_pal_base;
extern const u16 item_potion_tile_base;

extern const NgpcMetasprite item_potion_frame_0;

extern const MsprAnimFrame item_potion_anim[];
extern const u8 item_potion_anim_count;

#endif /* ITEM_POTION_MSPR_H */
