/* Generated by ngpc_sprite_export.py - do not edit */

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

/* Runtime note: call ngpc_mspr_draw(..., SPR_FRONT|optional flips). */

const u16 item_potion_tiles_count = 32u;
const u16 item_potion_tiles[] = {
    0x00AA, 0x002A, 0x000A, 0x000A, 0x0009, 0x0025, 0x029F, 0x097F, 0xAA00, 0xA800, 0xA000, 0xA000,
    0x6000, 0x5800, 0x5680, 0x5560, 0x25FD, 0x97F5, 0x97F5, 0x97F5, 0x25F5, 0x095D, 0x0295, 0x002A,
    0x5558, 0x5556, 0x5556, 0x5556, 0x5558, 0x5560, 0x5680, 0xA800
};

const u8 item_potion_palette_count = 1u;
const u16 item_potion_palettes[] = {
    0x0000, 0x011D, 0x0BA3, 0x055D
};

const u8 item_potion_pal_base = 12u;

const u16 item_potion_tile_base = 218u;

const NgpcMetasprite item_potion_frame_0 = {
    4u, 16u, 16u,
    {
        { 0, 0, 218, 12, 0 },
        { 8, 0, 219, 12, 0 },
        { 0, 8, 220, 12, 0 },
        { 8, 8, 221, 12, 0 }
    }
};

const MsprAnimFrame item_potion_anim[] = {
    { &item_potion_frame_0, 6 }
};

const u8 item_potion_anim_count = 1u;
