/* Generated by ngpc_sprite_export.py - do not edit */

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

/* Runtime note: call ngpc_mspr_draw(..., SPR_FRONT|optional flips). */

const u16 item_antidote_tiles_count = 32u;
const u16 item_antidote_tiles[] = {
    0x0055, 0x0055, 0x0015, 0x001A, 0x001E, 0x001A, 0x001A, 0x001A, 0x5500, 0x5500, 0x5400, 0xA400,
    0xA400, 0xB400, 0xA400, 0xE400, 0x001A, 0x001A, 0x001E, 0x001A, 0x001A, 0x001B, 0x0006, 0x0001,
    0xA400, 0xB400, 0xA400, 0xA400, 0xB400, 0xA400, 0x9000, 0x4000
};

const u8 item_antidote_palette_count = 1u;
const u16 item_antidote_palettes[] = {
    0x0000, 0x0BA3, 0x0393, 0x04B3
};

const u8 item_antidote_pal_base = 13u;

const u16 item_antidote_tile_base = 222u;

const NgpcMetasprite item_antidote_frame_0 = {
    4u, 16u, 16u,
    {
        { 0, 0, 222, 13, 0 },
        { 8, 0, 223, 13, 0 },
        { 0, 8, 224, 13, 0 },
        { 8, 8, 225, 13, 0 }
    }
};

const MsprAnimFrame item_antidote_anim[] = {
    { &item_antidote_frame_0, 6 }
};

const u8 item_antidote_anim_count = 1u;
