/* Generated by ngpc_sprite_export.py - do not edit */

#ifndef ITEM_ANTIDOTE_MSPR_H
#define ITEM_ANTIDOTE_MSPR_H

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

extern const u16 item_antidote_tiles_count;
extern const u16 NGP_FAR item_antidote_tiles[];

extern const u8 item_antidote_palette_count;
extern const u16 NGP_FAR item_antidote_palettes[];
extern const u8 item_antidote_pal_base;
extern const u16 item_antidote_tile_base;

extern const NgpcMetasprite item_antidote_frame_0;

extern const MsprAnimFrame item_antidote_anim[];
extern const u8 item_antidote_anim_count;

#endif /* ITEM_ANTIDOTE_MSPR_H */
