/* Generated by ngpc_sprite_export.py - do not edit */

#ifndef LIME_SHEET_MSPR_H
#define LIME_SHEET_MSPR_H

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

extern const u16 lime_sheet_tiles_count;
extern const u16 NGP_FAR lime_sheet_tiles[];

extern const u8 lime_sheet_palette_count;
extern const u16 NGP_FAR lime_sheet_palettes[];
extern const u8 lime_sheet_pal_base;
extern const u16 lime_sheet_tile_base;

extern const NgpcMetasprite lime_sheet_frame_0;
extern const NgpcMetasprite lime_sheet_frame_1;
extern const NgpcMetasprite lime_sheet_frame_2;
extern const NgpcMetasprite lime_sheet_frame_3;
extern const NgpcMetasprite lime_sheet_frame_4;
extern const NgpcMetasprite lime_sheet_frame_5;

extern const MsprAnimFrame lime_sheet_anim[];
extern const u8 lime_sheet_anim_count;

#endif /* LIME_SHEET_MSPR_H */
