/* Generated by ngpc_tilemap.py - do not edit */

#include "ngpc_types.h"

/* Image: 8x8 px (1x1 tiles) */
/* Tiles: 1 unique (8 words) */
/* Palettes: 1 */

const u16 map_jonction_map_w = 1u;
const u16 map_jonction_map_h = 1u;
const u16 map_jonction_map_len = 1u;

const u8 map_jonction_palette_count = 1u;
const u16 map_jonction_palettes[] = {
    0x0000, 0x0FFF, 0x0000, 0x0000
};

const u16 map_jonction_tiles_count = 8u;
const u16 map_jonction_tiles[] = {
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x5555, 0x5555
};

const u16 map_jonction_map_tiles[] = {
    0x0000
};

const u8 map_jonction_map_pals[] = {
    0x00
};
