/* Generated by ngpc_sprite_export.py - do not edit */

#ifndef MAP_PLAYER_POSITION_MSPR_H
#define MAP_PLAYER_POSITION_MSPR_H

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

extern const u16 map_player_position_tiles_count;
extern const u16 NGP_FAR map_player_position_tiles[];

extern const u8 map_player_position_palette_count;
extern const u16 NGP_FAR map_player_position_palettes[];
extern const u8 map_player_position_pal_base;
extern const u16 map_player_position_tile_base;

extern const NgpcMetasprite map_player_position_frame_0;
extern const NgpcMetasprite map_player_position_frame_1;

extern const MsprAnimFrame map_player_position_anim[];
extern const u8 map_player_position_anim_count;

#endif /* MAP_PLAYER_POSITION_MSPR_H */
