/* Generated by ngpc_sprite_export.py - do not edit */

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

/* Runtime note: call ngpc_mspr_draw(..., SPR_FRONT|optional flips). */

const u16 map_player_position_tiles_count = 8u;
const u16 map_player_position_tiles[] = {
    0x0550, 0x1AF4, 0x1AF4, 0x1AF4, 0x1AF4, 0x06D0, 0x0140, 0x0000
};

const u8 map_player_position_palette_count = 2u;
const u16 map_player_position_palettes[] = {
    0x0000, 0x0000, 0x0666, 0x0878, 0x0000, 0x0000, 0x0555, 0x0666
};

const u8 map_player_position_pal_base = 8u;

const u16 map_player_position_tile_base = 384u;

const NgpcMetasprite map_player_position_frame_0 = {
    1u, 8u, 8u,
    {
        { 0, 0, 384, 8, 0 }
    }
};

const NgpcMetasprite map_player_position_frame_1 = {
    1u, 8u, 8u,
    {
        { 0, 0, 384, 9, 0 }
    }
};

const MsprAnimFrame map_player_position_anim[] = {
    { &map_player_position_frame_0, 30 },
    { &map_player_position_frame_1, 30 }
};

const u8 map_player_position_anim_count = 2u;
