/* Generated by ngpc_tilemap.py - do not edit */

#ifndef MAP_JONCTION_TILEMAP_H
#define MAP_JONCTION_TILEMAP_H

#include "ngpc_types.h"

extern const u16 map_jonction_map_w;
extern const u16 map_jonction_map_h;
extern const u16 map_jonction_map_len;

extern const u8 map_jonction_palette_count;
extern const u16 NGP_FAR map_jonction_palettes[];

extern const u16 map_jonction_tiles_count;
extern const u16 NGP_FAR map_jonction_tiles[];

extern const u16 NGP_FAR map_jonction_map_tiles[];
extern const u8 NGP_FAR map_jonction_map_pals[];

#endif /* MAP_JONCTION_TILEMAP_H */
