/* Generated by ngpc_tilemap.py - do not edit */

#ifndef MAP_ROOM_TILEMAP_H
#define MAP_ROOM_TILEMAP_H

#include "ngpc_types.h"

extern const u16 map_room_map_w;
extern const u16 map_room_map_h;
extern const u16 map_room_map_len;

extern const u8 map_room_palette_count;
extern const u16 NGP_FAR map_room_palettes[];

extern const u16 map_room_tiles_count;
extern const u16 NGP_FAR map_room_tiles[];

extern const u16 NGP_FAR map_room_map_tiles[];
extern const u8 NGP_FAR map_room_map_pals[];

#endif /* MAP_ROOM_TILEMAP_H */
