/* Generated by ngpc_tilemap.py - do not edit */

#include "ngpc_types.h"

/* Image: 24x24 px (3x3 tiles) */
/* Tiles: 1 unique (8 words) */
/* Palettes: 1 */

const u16 map_room_map_w = 3u;
const u16 map_room_map_h = 3u;
const u16 map_room_map_len = 9u;

const u8 map_room_palette_count = 1u;
const u16 map_room_palettes[] = {
    0x0000, 0x0FFF, 0x0000, 0x0000
};

const u16 map_room_tiles_count = 8u;
const u16 map_room_tiles[] = {
    0x5555, 0x5555, 0x5555, 0x5555, 0x5555, 0x5555, 0x5555, 0x5555
};

const u16 map_room_map_tiles[] = {
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000
};

const u8 map_room_map_pals[] = {
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};
