/* Generated by ngpc_tilemap.py (dual-layer) - do not edit */

#ifndef MENU_PAUSE_TILEMAP_H
#define MENU_PAUSE_TILEMAP_H

#include "ngpc_types.h"

/* Shared tile data */
extern const u16 menu_pause_tiles_count;
extern const u16 NGP_FAR menu_pause_tiles[];

/* SCR1 (front) */
extern const u16 menu_pause_scr1_map_w;
extern const u16 menu_pause_scr1_map_h;
extern const u16 menu_pause_scr1_map_len;

extern const u8 menu_pause_scr1_palette_count;
extern const u16 NGP_FAR menu_pause_scr1_palettes[];

extern const u16 NGP_FAR menu_pause_scr1_map_tiles[];
extern const u8 NGP_FAR menu_pause_scr1_map_pals[];

/* SCR2 (back) */
extern const u16 menu_pause_scr2_map_w;
extern const u16 menu_pause_scr2_map_h;
extern const u16 menu_pause_scr2_map_len;

extern const u8 menu_pause_scr2_palette_count;
extern const u16 NGP_FAR menu_pause_scr2_palettes[];

extern const u16 NGP_FAR menu_pause_scr2_map_tiles[];
extern const u8 NGP_FAR menu_pause_scr2_map_pals[];

#endif /* MENU_PAUSE_TILEMAP_H */
