/* Generated by ngpc_tilemap.py (dual-layer) - do not edit */

#ifndef MENU_KUROI_DOKUTSU_TILEMAP_H
#define MENU_KUROI_DOKUTSU_TILEMAP_H

#include "ngpc_types.h"

/* Shared tile data */
extern const u16 menu_kuroi_dokutsu_tiles_count;
extern const u16 NGP_FAR menu_kuroi_dokutsu_tiles[];

/* SCR1 (front) */
extern const u16 menu_kuroi_dokutsu_scr1_map_w;
extern const u16 menu_kuroi_dokutsu_scr1_map_h;
extern const u16 menu_kuroi_dokutsu_scr1_map_len;

extern const u8 menu_kuroi_dokutsu_scr1_palette_count;
extern const u16 NGP_FAR menu_kuroi_dokutsu_scr1_palettes[];

extern const u16 NGP_FAR menu_kuroi_dokutsu_scr1_map_tiles[];
extern const u8 NGP_FAR menu_kuroi_dokutsu_scr1_map_pals[];

/* SCR2 (back) */
extern const u16 menu_kuroi_dokutsu_scr2_map_w;
extern const u16 menu_kuroi_dokutsu_scr2_map_h;
extern const u16 menu_kuroi_dokutsu_scr2_map_len;

extern const u8 menu_kuroi_dokutsu_scr2_palette_count;
extern const u16 NGP_FAR menu_kuroi_dokutsu_scr2_palettes[];

extern const u16 NGP_FAR menu_kuroi_dokutsu_scr2_map_tiles[];
extern const u8 NGP_FAR menu_kuroi_dokutsu_scr2_map_pals[];

#endif /* MENU_KUROI_DOKUTSU_TILEMAP_H */
