/* Generated by ngpc_sprite_export.py - do not edit */

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

/* Runtime note: call ngpc_mspr_draw(..., SPR_FRONT|optional flips). */

const u16 menu_level_lock_tiles_count = 32u;
const u16 menu_level_lock_tiles[] = {
    0x0000, 0x0000, 0x0155, 0x05AA, 0x0695, 0x069A, 0x06AA, 0x0655, 0x0000, 0x0000, 0x5500, 0xA940,
    0x5AC0, 0xBAC0, 0xAAC0, 0x56C0, 0x067A, 0x067A, 0x067E, 0x067F, 0x017F, 0x01FF, 0x0000, 0x0000,
    0x9EC0, 0x9EC0, 0x7EC0, 0xFEC0, 0xFF00, 0xFF00, 0x0000, 0x0000
};

const u8 menu_level_lock_palette_count = 1u;
const u16 menu_level_lock_palettes[] = {
    0x0000, 0x0875, 0x0000, 0x0876
};

const u8 menu_level_lock_pal_base = 1u;

const u16 menu_level_lock_tile_base = 144u;

const NgpcMetasprite menu_level_lock_frame_0 = {
    4u, 16u, 16u,
    {
        { 0, 0, 144, 1, 0 },
        { 8, 0, 145, 1, 0 },
        { 0, 8, 146, 1, 0 },
        { 8, 8, 147, 1, 0 }
    }
};

const MsprAnimFrame menu_level_lock_anim[] = {
    { &menu_level_lock_frame_0, 8 }
};

const u8 menu_level_lock_anim_count = 1u;
