/* Generated by ngpc_sprite_export.py - do not edit */

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

/* Runtime note: call ngpc_mspr_draw(..., SPR_FRONT|optional flips). */

const u16 menu_level_pointer_tiles_count = 16u;
const u16 menu_level_pointer_tiles[] = {
    0x0000, 0x0001, 0x0006, 0x001B, 0x006F, 0x01AA, 0x0155, 0x0000, 0x0000, 0x0000, 0x4000, 0x9000,
    0xE400, 0xA900, 0x5500, 0x0000
};

const u8 menu_level_pointer_palette_count = 1u;
const u16 menu_level_pointer_palettes[] = {
    0x0000, 0x02AD, 0x0B52, 0x0F82
};

const u8 menu_level_pointer_pal_base = 0u;

const u16 menu_level_pointer_tile_base = 140u;

const NgpcMetasprite menu_level_pointer_frame_0 = {
    2u, 16u, 8u,
    {
        { 0, 0, 140, 0, 0 },
        { 8, 0, 141, 0, 0 }
    }
};

const MsprAnimFrame menu_level_pointer_anim[] = {
    { &menu_level_pointer_frame_0, 8 }
};

const u8 menu_level_pointer_anim_count = 1u;
