/* Generated by ngpc_sprite_export.py - do not edit */

#ifndef MENU_LEVEL_LOCK_MSPR_H
#define MENU_LEVEL_LOCK_MSPR_H

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

extern const u16 menu_level_lock_tiles_count;
extern const u16 NGP_FAR menu_level_lock_tiles[];

extern const u8 menu_level_lock_palette_count;
extern const u16 NGP_FAR menu_level_lock_palettes[];
extern const u8 menu_level_lock_pal_base;
extern const u16 menu_level_lock_tile_base;

extern const NgpcMetasprite menu_level_lock_frame_0;

extern const MsprAnimFrame menu_level_lock_anim[];
extern const u8 menu_level_lock_anim_count;

#endif /* MENU_LEVEL_LOCK_MSPR_H */
