/* Generated by ngpc_tilemap.py - do not edit */

#ifndef MENU_SELECT_START_TILEMAP_H
#define MENU_SELECT_START_TILEMAP_H

#include "ngpc_types.h"

extern const u16 menu_select_start_map_w;
extern const u16 menu_select_start_map_h;
extern const u16 menu_select_start_map_len;

extern const u8 menu_select_start_palette_count;
extern const u16 NGP_FAR menu_select_start_palettes[];

extern const u16 menu_select_start_tiles_count;
extern const u16 NGP_FAR menu_select_start_tiles[];

extern const u16 NGP_FAR menu_select_start_map_tiles[];
extern const u8 NGP_FAR menu_select_start_map_pals[];

#endif /* MENU_SELECT_START_TILEMAP_H */
