/* Generated by ngpc_sprite_export.py - do not edit */

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

/* Runtime note: call ngpc_mspr_draw(..., SPR_FRONT|optional flips). */

const u16 player_topdown_tiles_count = 432u;
const u16 player_topdown_tiles[] = {
    0x0001, 0x0008, 0x0012, 0x0010, 0x0068, 0x507F, 0x6410, 0x7910, 0x5540, 0x2820, 0x2884, 0xAA04,
    0x3C29, 0xFFFD, 0x0004, 0x4104, 0x1E50, 0x0794, 0x01C5, 0x0040, 0x0014, 0x0005, 0x0006, 0x0001,
    0x4104, 0x0014, 0x5551, 0x0001, 0x5505, 0x4104, 0xF450, 0x5400, 0x1E50, 0x0794, 0x01C5, 0x0040,
    0x0054, 0x0015, 0x0005, 0x0000, 0x4104, 0x0014, 0x5551, 0x0001, 0x5505, 0x6900, 0x5B50, 0x1540,
    0x0001, 0x0008, 0x0012, 0x0010, 0x1468, 0x197F, 0x1D10, 0x0650, 0x0790, 0x0194, 0x01C5, 0x0045,
    0x0014, 0x0011, 0x0010, 0x0005, 0x4104, 0x0015, 0x5551, 0x5551, 0x1415, 0x4144, 0x1404, 0x4150,
    0x0055, 0x020A, 0x048A, 0x042A, 0x044A, 0x0515, 0x1502, 0x4142, 0x5000, 0x0800, 0x2100, 0x8100,
    0x1100, 0x6500, 0xA500, 0x9445, 0x5515, 0x4502, 0x1512, 0x0542, 0x0152, 0x0115, 0x01F5, 0x0154,
    0x6559, 0xA56D, 0x64B4, 0x94D0, 0x5540, 0x5400, 0x5000, 0x0000, 0x5515, 0x4502, 0x1512, 0x0542,
    0x0152, 0x0155, 0x0055, 0x0001, 0x6559, 0xA56D, 0x64B4, 0x94D0, 0x5540, 0x4400, 0xF400, 0x5400,
    0x5515, 0x4502, 0x1512, 0x0542, 0x0152, 0x0155, 0x01A5, 0x0150, 0x6559, 0xA56D, 0x64B4, 0x94D0,
    0x5540, 0x4400, 0xA400, 0x5400, 0x001A, 0x0060, 0x0182, 0x01FC, 0x01C0, 0x01FF, 0x0044, 0x1444,
    0xAA40, 0x0090, 0xA824, 0x03F4, 0x003D, 0xFFFD, 0x0554, 0x01B4, 0x1940, 0x0650, 0x01D5, 0x0075,
    0x005D, 0x01B4, 0x007D, 0x0015, 0x01B4, 0x05B4, 0x55B4, 0x0090, 0x00B4, 0x1074, 0x55D4, 0x0050,
    0x1940, 0x0650, 0x01D5, 0x0075, 0x001D, 0x0004, 0x0007, 0x0001, 0x01B4, 0x05B4, 0x55B4, 0x0190,
    0x01B4, 0x1574, 0xFD10, 0x5400, 0xAA40, 0x0090, 0xA824, 0x03F4, 0x003D, 0xFFFD, 0x0550, 0x01B4,
    0x01AA, 0x0600, 0x182A, 0x1FC0, 0x7C00, 0x7FFF, 0x1550, 0x1E40, 0xA400, 0x0900, 0x8240, 0x3F40,
    0x0340, 0xFF40, 0x1100, 0x1100, 0x1E40, 0x1E50, 0x1E55, 0x1600, 0x1E00, 0x1D00, 0x1755, 0x0500,
    0x0100, 0x0400, 0x5000, 0x5554, 0xFEA9, 0x5554, 0x7D00, 0x5400, 0x1E40, 0x1E50, 0x1E55, 0x1641,
    0x1E43, 0x1D55, 0x047F, 0x0015, 0x0100, 0x0400, 0x5000, 0x5550, 0xFAA4, 0x5550, 0xD000, 0x4000,
    0x01AA, 0x0600, 0x182A, 0x1FC0, 0x7C00, 0x7FFF, 0x0550, 0x1E40, 0x0000, 0x0002, 0x000C, 0x000E,
    0x0003, 0x0000, 0x0005, 0x0005, 0x0000, 0x8280, 0x8230, 0x00B0, 0xC3C0, 0x0000, 0x5550, 0x1450,
    0x0005, 0x0001, 0x0010, 0x001A, 0x0003, 0x0000, 0x0000, 0x0000, 0x1450, 0x5540, 0x0008, 0xAAAC,
    0x0050, 0x3C50, 0x0000, 0x0000, 0x1450, 0x5540, 0x0008, 0xAAAC, 0x0050, 0x0050, 0x0000, 0x0000,
    0x0005, 0x0001, 0x0010, 0x0010, 0x0002, 0x000C, 0x000F, 0x0000, 0x1450, 0x5540, 0x0004, 0x0004,
    0x8280, 0x2830, 0xC3F0, 0x0000, 0x0000, 0x00A0, 0x0320, 0x03C0, 0x0330, 0x0000, 0x0000, 0x2800,
    0x0000, 0xA000, 0x8C00, 0x3C00, 0xCC00, 0x0000, 0x0000, 0x0200, 0x0000, 0x1000, 0x0000, 0x0000,
    0x0000, 0x0080, 0x0000, 0x0000, 0x0000, 0x0000, 0x0100, 0x0100, 0x0000, 0x0000, 0x0000, 0x0000,
    0x0000, 0x1000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0100, 0x0100,
    0x0000, 0x2000, 0x0000, 0x0000, 0x0000, 0x000F, 0x003C, 0x0002, 0x002A, 0x0000, 0x0011, 0x0011,
    0x0000, 0xFF00, 0x03C0, 0xA800, 0xAA80, 0x0000, 0x5000, 0x5400, 0x0015, 0x0005, 0x0000, 0x0000,
    0x0000, 0x0003, 0x0000, 0x0000, 0x5400, 0x5000, 0x0000, 0xAA00, 0xB500, 0xC500, 0x0000, 0x0000,
    0x5400, 0x5000, 0x0000, 0x9400, 0xD400, 0xC000, 0x0000, 0x0000, 0x0000, 0x00FF, 0x03C0, 0x002A,
    0x02AA, 0x0000, 0x0005, 0x0015, 0x0000, 0xF000, 0x3C00, 0x8000, 0xA800, 0x0000, 0x4400, 0x4400,
    0x0015, 0x0005, 0x0000, 0x00AA, 0x00F5, 0x00F5, 0x0000, 0x0000, 0x5400, 0x5000, 0x0000, 0x0000,
    0x0000, 0x0000, 0x0000, 0x0000, 0x0015, 0x0005, 0x0000, 0x0014, 0x0014, 0x0000, 0x0000, 0x0000
};

const u8 player_topdown_palette_count = 2u;
const u16 player_topdown_palettes[] = {
    0x0000, 0x0111, 0x0999, 0x0777, 0x0000, 0x079B, 0x012A, 0x0128
};

const u8 player_topdown_pal_base = 0u;

const u16 player_topdown_tile_base = 256u;

const NgpcMetasprite player_topdown_frame_0 = {
    4u, 16u, 16u,
    {
        { 0, 0, 256, 0, 0 },
        { 8, 0, 257, 0, 0 },
        { 0, 8, 258, 0, 0 },
        { 8, 8, 259, 0, 0 }
    }
};

const NgpcMetasprite player_topdown_frame_1 = {
    4u, 16u, 16u,
    {
        { 0, 0, 256, 0, 0 },
        { 8, 0, 257, 0, 0 },
        { 0, 8, 260, 0, 0 },
        { 8, 8, 261, 0, 0 }
    }
};

const NgpcMetasprite player_topdown_frame_2 = {
    4u, 16u, 16u,
    {
        { 0, 0, 262, 0, 0 },
        { 8, 0, 257, 0, 0 },
        { 0, 8, 263, 0, 0 },
        { 8, 8, 264, 0, 0 }
    }
};

const NgpcMetasprite player_topdown_frame_3 = {
    4u, 16u, 16u,
    {
        { 0, 0, 265, 0, 0 },
        { 8, 0, 266, 0, 0 },
        { 0, 8, 267, 0, 0 },
        { 8, 8, 268, 0, 0 }
    }
};

const NgpcMetasprite player_topdown_frame_4 = {
    4u, 16u, 16u,
    {
        { 0, 0, 265, 0, 0 },
        { 8, 0, 266, 0, 0 },
        { 0, 8, 269, 0, 0 },
        { 8, 8, 270, 0, 0 }
    }
};

const NgpcMetasprite player_topdown_frame_5 = {
    4u, 16u, 16u,
    {
        { 0, 0, 265, 0, 0 },
        { 8, 0, 266, 0, 0 },
        { 0, 8, 271, 0, 0 },
        { 8, 8, 272, 0, 0 }
    }
};

const NgpcMetasprite player_topdown_frame_6 = {
    4u, 16u, 16u,
    {
        { 0, 0, 273, 0, 0 },
        { 8, 0, 274, 0, 0 },
        { 0, 8, 275, 0, 0 },
        { 8, 8, 276, 0, 0 }
    }
};

const NgpcMetasprite player_topdown_frame_7 = {
    4u, 16u, 16u,
    {
        { 0, 0, 273, 0, 0 },
        { 8, 0, 274, 0, 0 },
        { 0, 8, 277, 0, 0 },
        { 8, 8, 278, 0, 0 }
    }
};

const NgpcMetasprite player_topdown_frame_8 = {
    4u, 16u, 16u,
    {
        { 0, 0, 273, 0, 0 },
        { 8, 0, 279, 0, 0 },
        { 0, 8, 275, 0, 0 },
        { 8, 8, 276, 0, 0 }
    }
};

const NgpcMetasprite player_topdown_frame_9 = {
    4u, 16u, 16u,
    {
        { 0, 0, 280, 0, 0 },
        { 8, 0, 281, 0, 0 },
        { 0, 8, 282, 0, 0 },
        { 8, 8, 283, 0, 0 }
    }
};

const NgpcMetasprite player_topdown_frame_10 = {
    4u, 16u, 16u,
    {
        { 0, 0, 280, 0, 0 },
        { 8, 0, 281, 0, 0 },
        { 0, 8, 284, 0, 0 },
        { 8, 8, 285, 0, 0 }
    }
};

const NgpcMetasprite player_topdown_frame_11 = {
    4u, 16u, 16u,
    {
        { 0, 0, 286, 0, 0 },
        { 8, 0, 281, 0, 0 },
        { 0, 8, 282, 0, 0 },
        { 8, 8, 283, 0, 0 }
    }
};

const MsprAnimFrame player_topdown_anim[] = {
    { &player_topdown_frame_0, 8 },
    { &player_topdown_frame_1, 8 },
    { &player_topdown_frame_2, 8 },
    { &player_topdown_frame_3, 8 },
    { &player_topdown_frame_4, 8 },
    { &player_topdown_frame_5, 8 },
    { &player_topdown_frame_6, 8 },
    { &player_topdown_frame_7, 8 },
    { &player_topdown_frame_8, 8 },
    { &player_topdown_frame_9, 8 },
    { &player_topdown_frame_10, 8 },
    { &player_topdown_frame_11, 8 }
};

const u8 player_topdown_anim_count = 12u;

const NgpcMetasprite player_topdown_layer1_frame_0 = {
    4u, 16u, 16u,
    {
        { 0, 0, 287, 1, 0 },
        { 8, 0, 288, 1, 0 },
        { 0, 8, 289, 1, 0 },
        { 8, 8, 290, 1, 0 }
    }
};

const NgpcMetasprite player_topdown_layer1_frame_1 = {
    4u, 16u, 16u,
    {
        { 0, 0, 287, 1, 0 },
        { 8, 0, 288, 1, 0 },
        { 0, 8, 289, 1, 0 },
        { 8, 8, 291, 1, 0 }
    }
};

const NgpcMetasprite player_topdown_layer1_frame_2 = {
    4u, 16u, 16u,
    {
        { 0, 0, 287, 1, 0 },
        { 8, 0, 288, 1, 0 },
        { 0, 8, 292, 1, 0 },
        { 8, 8, 293, 1, 0 }
    }
};

const NgpcMetasprite player_topdown_layer1_frame_3 = {
    4u, 16u, 16u,
    {
        { 0, 0, 294, 1, 0 },
        { 8, 0, 295, 1, 0 },
        { 0, 8, 296, 1, 0 },
        { 8, 8, 297, 1, 0 }
    }
};

const NgpcMetasprite player_topdown_layer1_frame_4 = {
    4u, 16u, 16u,
    {
        { 0, 0, 294, 1, 0 },
        { 8, 0, 295, 1, 0 },
        { 0, 8, 298, 1, 0 },
        { 8, 8, 299, 1, 0 }
    }
};

const NgpcMetasprite player_topdown_layer1_frame_5 = {
    4u, 16u, 16u,
    {
        { 0, 0, 294, 1, 0 },
        { 8, 0, 295, 1, 0 },
        { 0, 8, 298, 1, 0 },
        { 8, 8, 299, 1, 0 }
    }
};

const NgpcMetasprite player_topdown_layer1_frame_6 = {
    4u, 16u, 16u,
    {
        { 0, 0, 300, 1, 0 },
        { 8, 0, 301, 1, 0 },
        { 0, 8, 302, 1, 0 },
        { 8, 8, 303, 1, 0 }
    }
};

const NgpcMetasprite player_topdown_layer1_frame_7 = {
    4u, 16u, 16u,
    {
        { 0, 0, 300, 1, 0 },
        { 8, 0, 301, 1, 0 },
        { 0, 8, 302, 1, 0 },
        { 8, 8, 304, 1, 0 }
    }
};

const NgpcMetasprite player_topdown_layer1_frame_8 = {
    4u, 16u, 16u,
    {
        { 0, 0, 300, 1, 0 },
        { 8, 0, 301, 1, 0 },
        { 0, 8, 302, 1, 0 },
        { 8, 8, 303, 1, 0 }
    }
};

const NgpcMetasprite player_topdown_layer1_frame_9 = {
    4u, 16u, 16u,
    {
        { 0, 0, 305, 1, 0 },
        { 8, 0, 306, 1, 0 },
        { 0, 8, 307, 1, 0 },
        { 8, 8, 308, 1, 0 }
    }
};

const NgpcMetasprite player_topdown_layer1_frame_10 = {
    4u, 16u, 16u,
    {
        { 0, 0, 305, 1, 0 },
        { 8, 0, 306, 1, 0 },
        { 0, 8, 309, 1, 0 },
        { 8, 8, 308, 1, 0 }
    }
};

const NgpcMetasprite player_topdown_layer1_frame_11 = {
    4u, 16u, 16u,
    {
        { 0, 0, 305, 1, 0 },
        { 8, 0, 306, 1, 0 },
        { 0, 8, 307, 1, 0 },
        { 8, 8, 308, 1, 0 }
    }
};

const MsprAnimFrame player_topdown_layer1_anim[] = {
    { &player_topdown_layer1_frame_0, 8 },
    { &player_topdown_layer1_frame_1, 8 },
    { &player_topdown_layer1_frame_2, 8 },
    { &player_topdown_layer1_frame_3, 8 },
    { &player_topdown_layer1_frame_4, 8 },
    { &player_topdown_layer1_frame_5, 8 },
    { &player_topdown_layer1_frame_6, 8 },
    { &player_topdown_layer1_frame_7, 8 },
    { &player_topdown_layer1_frame_8, 8 },
    { &player_topdown_layer1_frame_9, 8 },
    { &player_topdown_layer1_frame_10, 8 },
    { &player_topdown_layer1_frame_11, 8 }
};

const u8 player_topdown_layer1_anim_count = 12u;
