/* Generated by ngpc_sprite_export.py - do not edit */

#ifndef PLAYER_TOPDOWN_MSPR_H
#define PLAYER_TOPDOWN_MSPR_H

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

extern const u16 player_topdown_tiles_count;
extern const u16 NGP_FAR player_topdown_tiles[];

extern const u8 player_topdown_palette_count;
extern const u16 NGP_FAR player_topdown_palettes[];
extern const u8 player_topdown_pal_base;
extern const u16 player_topdown_tile_base;

extern const NgpcMetasprite player_topdown_frame_0;
extern const NgpcMetasprite player_topdown_frame_1;
extern const NgpcMetasprite player_topdown_frame_2;
extern const NgpcMetasprite player_topdown_frame_3;
extern const NgpcMetasprite player_topdown_frame_4;
extern const NgpcMetasprite player_topdown_frame_5;
extern const NgpcMetasprite player_topdown_frame_6;
extern const NgpcMetasprite player_topdown_frame_7;
extern const NgpcMetasprite player_topdown_frame_8;
extern const NgpcMetasprite player_topdown_frame_9;
extern const NgpcMetasprite player_topdown_frame_10;
extern const NgpcMetasprite player_topdown_frame_11;

extern const MsprAnimFrame player_topdown_anim[];
extern const u8 player_topdown_anim_count;

/* Dual-layer auto-split: draw player_topdown_layer1_anim at the same position after player_topdown_anim */
#define PLAYER_TOPDOWN_HAS_LAYER1 1

extern const NgpcMetasprite player_topdown_layer1_frame_0;
extern const NgpcMetasprite player_topdown_layer1_frame_1;
extern const NgpcMetasprite player_topdown_layer1_frame_2;
extern const NgpcMetasprite player_topdown_layer1_frame_3;
extern const NgpcMetasprite player_topdown_layer1_frame_4;
extern const NgpcMetasprite player_topdown_layer1_frame_5;
extern const NgpcMetasprite player_topdown_layer1_frame_6;
extern const NgpcMetasprite player_topdown_layer1_frame_7;
extern const NgpcMetasprite player_topdown_layer1_frame_8;
extern const NgpcMetasprite player_topdown_layer1_frame_9;
extern const NgpcMetasprite player_topdown_layer1_frame_10;
extern const NgpcMetasprite player_topdown_layer1_frame_11;

extern const MsprAnimFrame player_topdown_layer1_anim[];
extern const u8 player_topdown_layer1_anim_count;

#endif /* PLAYER_TOPDOWN_MSPR_H */
