/* Generated by ngpc_tilemap.py - do not edit */

#ifndef SALLE_02_TILEMAP_H
#define SALLE_02_TILEMAP_H

#include "ngpc_types.h"

extern const u16 salle_02_map_w;
extern const u16 salle_02_map_h;
extern const u16 salle_02_map_len;

extern const u8 salle_02_palette_count;
extern const u16 NGP_FAR salle_02_palettes[];

extern const u16 salle_02_tiles_count;
extern const u16 NGP_FAR salle_02_tiles[];

extern const u16 NGP_FAR salle_02_map_tiles[];
extern const u8 NGP_FAR salle_02_map_pals[];

#endif /* SALLE_02_TILEMAP_H */
