/* Generated by ngpc_tilemap.py - do not edit */

#ifndef SALLE_01_TILEMAP_H
#define SALLE_01_TILEMAP_H

#include "ngpc_types.h"

extern const u16 salle_01_map_w;
extern const u16 salle_01_map_h;
extern const u16 salle_01_map_len;

extern const u8 salle_01_palette_count;
extern const u16 NGP_FAR salle_01_palettes[];

extern const u16 salle_01_tiles_count;
extern const u16 NGP_FAR salle_01_tiles[];

extern const u16 NGP_FAR salle_01_map_tiles[];
extern const u8 NGP_FAR salle_01_map_pals[];

#endif /* SALLE_01_TILEMAP_H */
