/* Generated by ngpc_sprite_export.py - do not edit */

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

/* Runtime note: call ngpc_mspr_draw(..., SPR_FRONT|optional flips). */

const u16 select_menu_pause_tiles_count = 24u;
const u16 select_menu_pause_tiles[] = {
    0x0000, 0x0000, 0x5555, 0x6AAA, 0x5555, 0x0000, 0x0000, 0x0000, 0x1400, 0x1900, 0x5A40, 0xAA90,
    0x5A40, 0x1900, 0x1400, 0x0000, 0x0500, 0x0640, 0x5690, 0xAAA4, 0x5690, 0x0640, 0x0500, 0x0000
};

const u8 select_menu_pause_palette_count = 1u;
const u16 select_menu_pause_palettes[] = {
    0x0000, 0x0000, 0x03EF, 0x0000
};

const u8 select_menu_pause_pal_base = 10u;

const u16 select_menu_pause_tile_base = 240u;

const NgpcMetasprite select_menu_pause_frame_0 = {
    2u, 16u, 8u,
    {
        { 0, 0, 240, 10, 0 },
        { 8, 0, 241, 10, 0 }
    }
};

const NgpcMetasprite select_menu_pause_frame_1 = {
    2u, 16u, 8u,
    {
        { 0, 0, 240, 10, 0 },
        { 8, 0, 242, 10, 0 }
    }
};

const MsprAnimFrame select_menu_pause_anim[] = {
    { &select_menu_pause_frame_0, 6 },
    { &select_menu_pause_frame_1, 6 }
};

const u8 select_menu_pause_anim_count = 2u;
