/* Generated by ngpc_sprite_export.py - do not edit */

#ifndef SELECT_MENU_PAUSE_MSPR_H
#define SELECT_MENU_PAUSE_MSPR_H

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

extern const u16 select_menu_pause_tiles_count;
extern const u16 NGP_FAR select_menu_pause_tiles[];

extern const u8 select_menu_pause_palette_count;
extern const u16 NGP_FAR select_menu_pause_palettes[];
extern const u8 select_menu_pause_pal_base;
extern const u16 select_menu_pause_tile_base;

extern const NgpcMetasprite select_menu_pause_frame_0;
extern const NgpcMetasprite select_menu_pause_frame_1;

extern const MsprAnimFrame select_menu_pause_anim[];
extern const u8 select_menu_pause_anim_count;

#endif /* SELECT_MENU_PAUSE_MSPR_H */
