/* Generated by ngpc_sprite_export.py - do not edit */

#ifndef SKULL_MSPR_H
#define SKULL_MSPR_H

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

extern const u16 skull_tiles_count;
extern const u16 NGP_FAR skull_tiles[];

extern const u8 skull_palette_count;
extern const u16 NGP_FAR skull_palettes[];
extern const u8 skull_pal_base;
extern const u16 skull_tile_base;

extern const NgpcMetasprite skull_frame_0;
extern const NgpcMetasprite skull_frame_1;

extern const MsprAnimFrame skull_anim[];
extern const u8 skull_anim_count;

#endif /* SKULL_MSPR_H */
