/* Generated by ngpc_sprite_export.py - do not edit */

#ifndef SKULL_DEATH_MSPR_H
#define SKULL_DEATH_MSPR_H

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

extern const u16 skull_death_tiles_count;
extern const u16 NGP_FAR skull_death_tiles[];

extern const u8 skull_death_palette_count;
extern const u16 NGP_FAR skull_death_palettes[];
extern const u8 skull_death_pal_base;
extern const u16 skull_death_tile_base;

extern const NgpcMetasprite skull_death_frame_0;

extern const MsprAnimFrame skull_death_anim[];
extern const u8 skull_death_anim_count;

#endif /* SKULL_DEATH_MSPR_H */
