/* Generated by ngpc_sprite_export.py - do not edit */

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

/* Runtime note: call ngpc_mspr_draw(..., SPR_FRONT|optional flips). */

const u16 skull_tiles_count = 48u;
const u16 skull_tiles[] = {
    0x0001, 0x0007, 0x001A, 0x001A, 0x1015, 0x6416, 0x691A, 0x6906, 0x5400, 0xA900, 0xBE40, 0xAA40,
    0x9640, 0xA640, 0x6A54, 0x99A9, 0x1919, 0x1966, 0x1FD6, 0x7DD5, 0x1746, 0x0119, 0x0019, 0x0069,
    0x96DD, 0xA676, 0xA6FE, 0x96FE, 0xA6DE, 0x55A9, 0x0154, 0x0690, 0x0001, 0x0007, 0x001A, 0x041A,
    0x1815, 0x1916, 0x1A5A, 0x0646, 0x1A59, 0x1D66, 0x7FD6, 0x15D5, 0x0346, 0x0119, 0x0019, 0x0069
};

const u8 skull_palette_count = 2u;
const u16 skull_palettes[] = {
    0x0000, 0x0000, 0x0EEF, 0x0EFF, 0x0000, 0x0000, 0x0EEF, 0x0337
};

const u8 skull_pal_base = 6u;

const u16 skull_tile_base = 172u;

const NgpcMetasprite skull_frame_0 = {
    4u, 16u, 16u,
    {
        { 0, 0, 172, 6, 0 },
        { 8, 0, 173, 6, 0 },
        { 0, 8, 174, 7, 0 },
        { 8, 8, 175, 7, 0 }
    }
};

const NgpcMetasprite skull_frame_1 = {
    4u, 16u, 16u,
    {
        { 0, 0, 176, 6, 0 },
        { 8, 0, 173, 6, 0 },
        { 0, 8, 177, 7, 0 },
        { 8, 8, 175, 7, 0 }
    }
};

const MsprAnimFrame skull_anim[] = {
    { &skull_frame_0, 6 },
    { &skull_frame_1, 6 }
};

const u8 skull_anim_count = 2u;
