/* Generated by ngpc_sprite_export.py - do not edit */

#include "ngpc_types.h"
#include "ngpc_metasprite.h"

/* Runtime note: call ngpc_mspr_draw(..., SPR_FRONT|optional flips). */

const u16 skull_death_tiles_count = 32u;
const u16 skull_death_tiles[] = {
    0x02AA, 0x2AAA, 0xAAAA, 0xAAAA, 0xAAAA, 0xAFEA, 0xBFFA, 0x7FF5, 0xAA00, 0xAA80, 0xAAA0, 0xAAA0,
    0xAAA8, 0xAFE8, 0xBFF8, 0x7FF4, 0x7FF5, 0x5FD5, 0x555F, 0x555F, 0x155F, 0x0555, 0x05D5, 0x05D5,
    0x7FF4, 0x5FD4, 0xD554, 0xD554, 0xD550, 0x5540, 0x5D40, 0x5D40
};

const u8 skull_death_palette_count = 1u;
const u16 skull_death_palettes[] = {
    0x0000, 0x0ACD, 0x0DEE, 0x0000
};

const u8 skull_death_pal_base = 12u;

const u16 skull_death_tile_base = 192u;

const NgpcMetasprite skull_death_frame_0 = {
    4u, 16u, 16u,
    {
        { 0, 0, 192, 12, 0 },
        { 8, 0, 193, 12, 0 },
        { 0, 8, 194, 12, 0 },
        { 8, 8, 195, 12, 0 }
    }
};

const MsprAnimFrame skull_death_anim[] = {
    { &skull_death_frame_0, 6 }
};

const u8 skull_death_anim_count = 1u;
