/*
 * asset_pipeline_example.c - Runtime usage example for tilemap/sprite tools
 *
 * This file is documentation-by-example and is not compiled by default.
 * Adapt symbol names to your generated GraphX/*.c files.
 */

#include "../src/core/ngpc_hw.h"
#include "../src/gfx/ngpc_gfx.h"
#include "../src/gfx/ngpc_tilemap_blit.h"
#include "../src/fx/ngpc_lz.h"

/* Example symbols generated by tools/ngpc_tilemap.py (name: level1_bg). */
extern const u8  level1_bg_map_w;
extern const u8  level1_bg_map_h;
extern const u16 level1_bg_tiles_count;
extern const u16 level1_bg_tiles[];
extern const u16 level1_bg_map_tiles[];
extern const u8  level1_bg_map_pals[];
extern const u8  level1_bg_palette_count;
extern const u16 level1_bg_palettes[];

/* Optional compressed tiles from tools/ngpc_compress.py. */
extern const u16 level1_bg_tiles_lz_len;
extern const u8  level1_bg_tiles_lz[];

static void bg_apply_palettes(u8 plane)
{
    u8 p;
    for (p = 0; p < level1_bg_palette_count; ++p) {
        u16 off = (u16)p * 4;
        ngpc_gfx_set_palette(
            plane, p,
            level1_bg_palettes[off + 0],
            level1_bg_palettes[off + 1],
            level1_bg_palettes[off + 2],
            level1_bg_palettes[off + 3]
        );
    }
}

static void bg_draw_map(u8 plane, u16 tile_base)
{
    u8 x, y;
    u16 i = 0;

    for (y = 0; y < level1_bg_map_h; ++y) {
        for (x = 0; x < level1_bg_map_w; ++x) {
            u16 tile = tile_base + level1_bg_map_tiles[i];
            u8 pal = level1_bg_map_pals[i];
            ngpc_gfx_put_tile(plane, x, y, tile, pal);
            ++i;
        }
    }
}

/* Raw path: load generated tiles directly. */
void example_bg_load_raw(u8 plane, u16 tile_base)
{
    bg_apply_palettes(plane);
    /* Note (cc900 near/far model):
     * If your generated `const` assets live in ROM (0x200000+), pointers must be
     * treated as "far" to avoid reading from the wrong address.
     * The template configures this via `NGP_FAR=__far` + helper signatures.
     * If you still see corruption, prefer the macro-based blit functions below. */
    ngpc_gfx_load_tiles_at(level1_bg_tiles, level1_bg_tiles_count, tile_base);
    bg_draw_map(plane, tile_base);
}

/* Compressed path: load LZ-compressed tiles. */
void example_bg_load_lz(u8 plane, u16 tile_base)
{
    bg_apply_palettes(plane);
    ngpc_lz_to_tiles(level1_bg_tiles_lz, level1_bg_tiles_lz_len, tile_base);
    bg_draw_map(plane, tile_base);
}

/* Safe path (recommended): windjammer-style VRAM blit.
 * Note: these are plane-specific because they write directly to HW_SCRx_MAP. */
void example_bg_blit_scr1(u16 tile_base)
{
    NGP_TILEMAP_LOAD_TILES_VRAM(level1_bg, tile_base);
    NGP_TILEMAP_LOAD_PALETTES_SCR1(level1_bg);
    NGP_TILEMAP_PUT_MAP_SCR1(level1_bg, tile_base);
}

void example_bg_blit_scr2(u16 tile_base)
{
    NGP_TILEMAP_LOAD_TILES_VRAM(level1_bg, tile_base);
    NGP_TILEMAP_LOAD_PALETTES_SCR2(level1_bg);
    NGP_TILEMAP_PUT_MAP_SCR2(level1_bg, tile_base);
}
