#ifndef NGPC_GAME_VARS_H
#define NGPC_GAME_VARS_H

/*
 * ngpc_game_vars -- Persistent flags & variables for NGPC projects
 * =================================================================
 * 16 boolean flags (u8, 0/1) and 16 byte counters (u8, 0-255) that
 * survive scene transitions.
 *
 * Names and init values are defined in the PNG Manager project tab
 * ("Variables de jeu") and exported to GraphX/gen/ngpc_game_vars.h.
 *
 * Flags    : persistent booleans. set/clear/toggle via triggers or code.
 * Variables: persistent counters.  init value applied by ngpc_gv_init().
 *
 * ---------------------------------------------------------------------------
 * Installation:
 *   Copy ngpc_game_vars/ into src/
 *   Add  OBJS += src/ngpc_game_vars/ngpc_game_vars.rel  to the Makefile
 *   #include "ngpc_game_vars/ngpc_game_vars.h"
 *   In main.c, call ngpc_gv_init() once at game start (or via init_game_vars
 *   trigger action on scene 0).
 *   In your trigger dispatch loop, call:
 *       if (ngpc_gv_dispatch(t->action, t->a0, t->a1)) continue;
 * ---------------------------------------------------------------------------
 *
 * Typical usage:
 *
 *   // At game start:
 *   ngpc_gv_init();                     // apply default variable values
 *
 *   // In gameplay code:
 *   ngpc_gv_set_flag(GAME_FLAG_0);      // set flag 0 (e.g. "has_sword")
 *   if (ngpc_gv_get_flag(GAME_FLAG_0))  // check flag
 *   ngpc_gv_inc_var(GAME_VAR_0, 0);     // increment coins (no cap)
 *   u8 coins = ngpc_gv_get_var(GAME_VAR_0);
 *
 *   // In trigger dispatch:
 *   if (ngpc_gv_dispatch(t->action, t->a0, t->a1)) continue;
 *
 * Generated constants (from GraphX/gen/ngpc_game_vars.h):
 *   GAME_FLAG_0 .. GAME_FLAG_15 -- index constants for flags
 *   GAME_VAR_0  .. GAME_VAR_15  -- index constants for variables
 *   g_game_var_inits[16]        -- default init values array
 */

#include "ngpc_hw.h"  /* u8, u16, s8 */

/* Include the generated names/inits header if available. */
/* GraphX/gen/ngpc_game_vars.h is auto-generated by the PNG Manager export. */
/* It defines GAME_FLAG_0..15, GAME_VAR_0..15, and g_game_var_inits[16].   */

#define NGPC_GV_FLAG_COUNT 16u
#define NGPC_GV_VAR_COUNT  16u

/* Persistent state arrays -- zero-initialized at startup. */
extern u8 ngpc_gv_flags[NGPC_GV_FLAG_COUNT];
extern u8 ngpc_gv_vars[NGPC_GV_VAR_COUNT];

/*
 * ngpc_gv_init() -- Apply default variable values from g_game_var_inits[].
 * Also zeroes all flags.
 * Call once at game start, or wire to the init_game_vars trigger action.
 * If ngpc_game_vars.h was not exported yet, all variables default to 0.
 */
void ngpc_gv_init(void);

/* ---- Flags ------------------------------------------------------------ */

void ngpc_gv_set_flag(u8 idx);     /* Set flag idx to 1.                  */
void ngpc_gv_clear_flag(u8 idx);   /* Set flag idx to 0.                  */
void ngpc_gv_toggle_flag(u8 idx);  /* Invert flag idx.                    */
u8   ngpc_gv_get_flag(u8 idx);     /* Return current value (0 or 1).      */

/* ---- Variables -------------------------------------------------------- */

void ngpc_gv_set_var(u8 idx, u8 val);
/*
 * Increment variable idx. cap=0 means no cap (wraps at 255->0 naturally
 * per u8 arithmetic).  cap>0 means: only increment if current < cap.
 */
void ngpc_gv_inc_var(u8 idx, u8 cap);
void ngpc_gv_dec_var(u8 idx);      /* Decrement (floor at 0).             */
u8   ngpc_gv_get_var(u8 idx);      /* Return current value (0..255).      */

/* ---- Trigger dispatch helper ----------------------------------------- */

/*
 * Handle one trigger action for flags/variables.
 * Returns 1 if the action was handled, 0 if it is not a flags/vars action.
 *
 * Handled action IDs (matching scene_level_gen.py act_to_id):
 *   28 = set_flag      a0=flag_idx
 *   29 = clear_flag    a0=flag_idx
 *   30 = set_variable  a0=var_idx  a1=value
 *   31 = inc_variable  a0=var_idx  a1=cap (0=no cap)
 *   51 = dec_variable  a0=var_idx
 *   58 = toggle_flag   a0=flag_idx
 *   74 = init_game_vars (calls ngpc_gv_init)
 *
 * Usage in main.c trigger dispatch:
 *   if (ngpc_gv_dispatch(t->action, t->a0, t->a1)) continue;
 */
u8 ngpc_gv_dispatch(u8 action, u8 a0, u8 a1);

#endif /* NGPC_GAME_VARS_H */
