#ifndef NGPC_CAVEGEN_H
#define NGPC_CAVEGEN_H

/*
 * ngpc_cavegen -- Procedural cave generator (Cave Noir style)
 * ============================================================
 * Generates a 32x32-tile cave using a cellular automaton.
 * The full map is generated at level start; the game then
 * navigates it freely (scrolling, exploration, optional fog-of-war).
 *
 * Algorithm:
 *   1. Random fill (wall_pct % walls).
 *   2. Cellular smoothing x5 (5/4 rule: Moore neighborhood).
 *   3. Flood-fill from center to remove isolated regions.
 *   4. Placement: entry (left), exit (right), enemies, chests.
 *
 * NGPC constraints:
 *   - 32x32 map = 1024 bytes (fits within RAM budget).
 *   - Visible screen: 20x19 tiles -> use ngpc_cavegen_viewport().
 *   - No dynamic allocation.
 *   - Compatible with cc900/C89.
 *
 * Dependencies: ngpc_rng (optional/ngpc_rng/)
 *
 * Minimal usage:
 *
 *   NgpcCaveMap cave;
 *   ngpc_cavegen_generate(&cave, 0xAB12, 47, 8, 3);
 *
 *   u8 cam_x = cave.entry_x;
 *   u8 cam_y = (cave.entry_y > 9u) ? (u8)(cave.entry_y - 9u) : 0u;
 *
 *   u8 view[20 * 19];
 *   ngpc_cavegen_viewport(&cave, cam_x, cam_y, view);
 *   // Convert view[i] (CAVE_*) to an NGPC tile and write to VRAM
 *
 * Recommended wall_pct values:
 *   wall_pct = 47  (balanced natural cave)
 *   wall_pct = 40  (open cave, few walls)
 *   wall_pct = 55  (narrow cave, corridors)
 *   max_enemies = 6..12
 *   max_chests  = 2..5
 */

#include "ngpc_hw.h"              /* u8, u16, s8 */
#include "ngpc_rng/ngpc_rng.h"   /* NgpcRng */

/* ── Map dimensions ──────────────────────────────────────────────────── */

#define CAVEGEN_W   32u   /* cave width in tiles  */
#define CAVEGEN_H   32u   /* cave height in tiles */

/* ── Tile types ──────────────────────────────────────────────────────── */

#define CAVE_WALL    0u   /* wall (solid, impassable)    */
#define CAVE_FLOOR   1u   /* floor (passable)            */
#define CAVE_ENTRY   2u   /* player spawn point          */
#define CAVE_EXIT    3u   /* level exit (stair, door...) */
#define CAVE_CHEST   4u   /* chest / collectible         */
#define CAVE_ENEMY   5u   /* enemy spawn point           */

/*
 * NgpcCaveMap: complete cave map.
 * Total size: 32x32 + 8 = 1032 bytes.
 *
 * map[y * CAVEGEN_W + x] = CAVE_* for each tile.
 * entry_x/y and exit_x/y are tile coordinates within the map.
 */
typedef struct {
    u8  map[CAVEGEN_W * CAVEGEN_H]; /* 1024 bytes: CAVE_* per tile           */
    u8  entry_x;  /* tile column of the player entry (left side)             */
    u8  entry_y;  /* tile row    of the player entry                         */
    u8  exit_x;   /* tile column of the exit (right side)                    */
    u8  exit_y;   /* tile row    of the exit                                 */
    u8  enemy_count;  /* actual number of CAVE_ENEMY tiles placed            */
    u8  chest_count;  /* actual number of CAVE_CHEST tiles placed            */
    u16 seed;         /* seed used for generation                            */
} NgpcCaveMap;

/* ── Public API ──────────────────────────────────────────────────────── */

/*
 * Generate a complete cave.
 *
 *   out         : NgpcCaveMap to fill (caller-provided)
 *   seed        : generation seed (same seed = same cave)
 *   wall_pct    : initial wall density 0..100 (recommended: 45..50)
 *   max_enemies : max enemies to place in the cave (recommended: 6..12)
 *   max_chests  : max chests to place (recommended: 2..5)
 *
 * After the call:
 *   out->entry_x/y    = player spawn position
 *   out->exit_x/y     = exit position
 *   out->enemy_count  = enemies actually placed (may be < max_enemies)
 *   out->chest_count  = chests actually placed
 */
void ngpc_cavegen_generate(
    NgpcCaveMap *out,
    u16          seed,
    u8           wall_pct,
    u8           max_enemies,
    u8           max_chests
);

/*
 * Extract a 20x19-tile viewport for NGPC display.
 *
 *   m     : cave generated by ngpc_cavegen_generate()
 *   cam_x : left column of the viewport in the cave (0..CAVEGEN_W-20)
 *   cam_y : top row    of the viewport in the cave (0..CAVEGEN_H-19)
 *   out   : u8[20*19] array filled with CAVE_* values
 *
 * cam_x and cam_y are automatically clamped to valid bounds.
 * Convert each CAVE_* value to an NGPC tile index afterward:
 *   CAVE_WALL  -> tile_wall
 *   CAVE_FLOOR -> tile_floor
 *   etc.
 */
void ngpc_cavegen_viewport(
    const NgpcCaveMap *m,
    u8                 cam_x,
    u8                 cam_y,
    u8                *out
);

/*
 * Compute recommended camera bounds to center the view on (px, py).
 * px, py: player position in tiles.
 * Writes cam_x and cam_y clamped to [0, CAVEGEN_W-20] x [0, CAVEGEN_H-19].
 */
void ngpc_cavegen_cam_center(u8 px, u8 py, u8 *cam_x, u8 *cam_y);

#endif /* NGPC_CAVEGEN_H */
