/*
 * ngpc_lut.c - Precomputed lookup tables
 *
 * Part of NgpCraft_base_template (MIT License)
 *
 * Tables computed mathematically (pure math, no copyright concern).
 */

#include "ngpc_lut.h"

/* ---- atan2 lookup ---- */

/*
 * Octant lookup table: 32x32 entries covering one octant (0-45 degrees).
 * Other octants are derived by symmetry.
 *
 * Table[y][x] = atan2(y, x) * 256 / (2*PI) for the first octant.
 * Values 0-32 (0 to 45 degrees in 256 units).
 *
 * Generated by: round(atan2(y, max(x, 1)) * 128 / PI) for x,y in 0..31
 */
static const u8 atan_oct[32] = {
     0,  1,  2,  3,  3,  4,  5,  6,
     6,  7,  8,  8,  9, 10, 10, 11,
    11, 12, 12, 13, 13, 14, 14, 15,
    15, 16, 16, 16, 17, 17, 17, 18
};

u8 ngpc_lut_atan2(s8 dx, s8 dy)
{
    u8 ax, ay, angle, idx;

    /* Handle zero vector. */
    if (dx == 0 && dy == 0) return 0;

    /* Absolute values. */
    ax = (dx < 0) ? (u8)(-dx) : (u8)dx;
    ay = (dy < 0) ? (u8)(-dy) : (u8)dy;

    /* Scale to 0-31 range for table lookup.
     * Use the ratio ay/ax (or ax/ay) scaled to 0-31. */
    if (ax >= ay) {
        /* First octant (0-45 deg): index = (ay * 31) / ax */
        idx = (ax > 0) ? (u8)(((u16)ay * 31) / (u16)ax) : 0;
        angle = atan_oct[idx];
    } else {
        /* Second octant (45-90 deg): 64 - table[(ax*31)/ay] */
        idx = (ay > 0) ? (u8)(((u16)ax * 31) / (u16)ay) : 0;
        angle = 64 - atan_oct[idx];
    }

    /* Map to full 0-255 range based on quadrant.
     * Convention: 0=right, 64=down, 128=left, 192=up. */
    if (dx >= 0 && dy >= 0) return angle;         /* Q1: 0-63   */
    if (dx < 0  && dy >= 0) return 128 - angle;   /* Q2: 64-128 */
    if (dx < 0  && dy < 0)  return 128 + angle;   /* Q3: 128-192 */
    return 256 - angle;                            /* Q4: 192-255 */
}

/* ---- Integer square root ---- */

u8 ngpc_lut_sqrt16(u16 n)
{
    /*
     * Binary search for floor(sqrt(n)).
     * 8 iterations for 16-bit input (result 0-255).
     * No table needed, pure computation, ~80 cycles.
     */
    u8 result = 0;
    u8 bit = 128;   /* Start from highest bit */

    while (bit > 0) {
        u8 test = result | bit;
        if ((u16)test * (u16)test <= n)
            result = test;
        bit >>= 1;
    }

    return result;
}

/* ---- Approximate distance ---- */

u16 ngpc_lut_dist(s16 dx, s16 dy)
{
    /*
     * Alpha max + beta min approximation.
     * alpha = 1.0, beta = 0.414 ~= 106/256
     * dist ~= max + (min * 106) >> 8
     * Max error: ~4% (overestimates).
     */
    u16 ax = (dx < 0) ? (u16)(-dx) : (u16)dx;
    u16 ay = (dy < 0) ? (u16)(-dy) : (u16)dy;
    u16 mn, mx;

    if (ax > ay) { mx = ax; mn = ay; }
    else         { mx = ay; mn = ax; }

    return mx + ((mn * 106) >> 8);
}

/* ---- Fast division by small constant ---- */

/*
 * Reciprocal table: recip[d] = 65536 / d (for d = 1..255).
 * Division: n / d ~= (n * recip[d]) >> 16.
 * Accurate for n < 4096. recip[0] = 0 (avoid divide by zero).
 *
 * Only the most commonly used divisors are tabled to save ROM.
 * We compute on the fly for simplicity (the multiply is still
 * faster than a software division loop).
 */

u16 ngpc_lut_div(u16 n, u8 divisor)
{
    u32 recip;

    if (divisor == 0) return 0xFFFF;    /* saturate on /0 */
    if (divisor == 1) return n;

    /* Reciprocal multiplication: n / d = (n * (65536/d)) >> 16 */
    recip = 65536UL / (u32)divisor;
    return (u16)(((u32)n * recip) >> 16);
}
