#ifndef NGPC_DIALOG_H
#define NGPC_DIALOG_H

/*
 * ngpc_dialog -- Tilemap dialogue box
 * ===================================
 * Displays a dialogue box with typewriter text, optional encoded speaker
 * name, optional portrait-aware text layout, and up to 2 choices.
 *
 * NOTE ABOUT NGPCRAFT ENGINE COMPATIBILITY
 * ---------------------------------------
 * Sections marked "NGPCRAFT ENGINE COMPATIBILITY" are mainly present to stay
 * compatible with dialogue data generated by:
 *   - NgpCraft_engine/core/scene_level_gen.py
 *
 * Portrait sprite drawing itself is NOT handled by this module. In
 * NgpCraft Engine, that runtime glue is generated from:
 *   - NgpCraft_engine/core/template_integration.py
 *
 * If you use this module standalone with plain text only, you can comment
 * out or delete the marked sections below and keep a simpler base module.
 *
 * IMPORTANT:
 * For encoded speaker strings, use "\001Speaker\002Text" or the helper
 * string macros below. Avoid "\x01Speaker\x02Text" in C literals: \x
 * escapes can absorb following hex characters and corrupt the compiled text.
 */

#include "ngpc_hw.h"

/* Return values from ngpc_dialog_update(). */
#define DIALOG_RUNNING   0
#define DIALOG_DONE      1
#define DIALOG_CHOICE_0  2
#define DIALOG_CHOICE_1  3

/* Tunables. */
#ifndef DIALOG_TEXT_SPEED
#define DIALOG_TEXT_SPEED   2
#endif

#ifndef DIALOG_BLINK_PERIOD
#define DIALOG_BLINK_PERIOD 30
#endif

#ifndef DIALOG_MAX_LINES
#define DIALOG_MAX_LINES    3
#endif

#ifndef DIALOG_MAX_CHOICES
#define DIALOG_MAX_CHOICES  2
#endif

#ifndef DIALOG_ARROW_CHAR
#define DIALOG_ARROW_CHAR   '>'
#endif

/*
 * NGPCRAFT ENGINE COMPATIBILITY
 * -----------------------------
 * These marker helpers match the encoded speaker strings emitted by
 * NgpCraft Engine dialogue export.
 *
 * If you do not use encoded speaker strings, you may comment out or delete
 * this section and the matching parser block in ngpc_dialog.c.
 */
#ifndef DIALOG_SPEAKER_BEGIN_CHAR
#define DIALOG_SPEAKER_BEGIN_CHAR '\001'
#endif

#ifndef DIALOG_SPEAKER_END_CHAR
#define DIALOG_SPEAKER_END_CHAR   '\002'
#endif

#ifndef DIALOG_SPEAKER_BEGIN_STR
#define DIALOG_SPEAKER_BEGIN_STR  "\001"
#endif

#ifndef DIALOG_SPEAKER_END_STR
#define DIALOG_SPEAKER_END_STR    "\002"
#endif

/* Internal flags. */
#define _DLG_HAS_CHOICES  0x01
#define _DLG_TEXT_DONE    0x02
#define _DLG_OPEN         0x04

/*
 * NGPCRAFT ENGINE COMPATIBILITY
 * -----------------------------
 * Portrait-aware layout and encoded speaker support live here.
 *
 * Standalone users who only want plain text in a fixed box can comment out
 * or delete this section and the related layout code in ngpc_dialog.c.
 */
#define DIALOG_LAYOUT_PORTRAIT  0x01u

typedef struct {
    const char *text;
    const char *speaker;
    const char **choices;
    u8  plane;
    u8  bx, by;
    u8  bw, bh;
    u8  char_idx;
    u8  tick;
    u8  blink;
    u8  cursor;
    u8  n_choices;
    u8  layout_flags;
    u8  flags;
} NgpcDialog;

/* Opens the box and draws its frame unless DIALOG_NO_FRAME is defined. */
void ngpc_dialog_open(NgpcDialog *d,
                      u8 plane, u8 bx, u8 by, u8 bw, u8 bh, u8 pal);

/* Closes the box and clears the occupied tile area. */
void ngpc_dialog_close(NgpcDialog *d);

/*
 * Sets the dialogue text.
 *
 * Plain text:
 *   "Hello world"
 *
 * Encoded speaker format used by NgpCraft Engine:
 *   "\001Speaker\002Hello world"
 */
void ngpc_dialog_set_text(NgpcDialog *d, const char *text);

/*
 * NGPCRAFT ENGINE COMPATIBILITY
 * -----------------------------
 * Applies portrait-aware layout flags such as DIALOG_LAYOUT_PORTRAIT.
 *
 * If you do not use NgpCraft-style portrait layouts, you may comment out or
 * delete this declaration and the matching implementation block.
 */
void ngpc_dialog_set_layout(NgpcDialog *d, u8 flags);

/* Adds choices shown after the text is fully revealed. */
void ngpc_dialog_set_choices(NgpcDialog *d, const char **choices, u8 count);

/* Updates the box once per frame. */
u8 ngpc_dialog_update(NgpcDialog *d);

/* Small helpers. */
#define ngpc_dialog_is_open(d)   ((d)->flags & _DLG_OPEN)
#define ngpc_dialog_plane(d)     ((u8)((d)->plane & 0x03u))
#define ngpc_dialog_palette(d)   ((u8)(((d)->plane >> 2) & 0x0Fu))

#endif /* NGPC_DIALOG_H */
