#!/usr/bin/env python3
# -*- coding: ascii -*-
"""
export_caisse.py

Convertit GraphX/caisse.png (16x16 RGBA) en GraphX/caisse_tiles.c/.h.

Format NGPC 2bpp, palette identique a hent (marrons) :
  C0 = 0x0000 transparent
  C1 = 0x0135 marron fonce (outline)
  C2 = 0x0269 marron clair (corps)
  C3 = 0x0000 inutilise

Chaque PNG 16x16 = 4 sous-tiles 8x8 (TL TR BL BR), 8 u16 chacun.

Usage : depuis la racine du projet :
    python tools/export_caisse.py
"""

import os
import sys

try:
    from PIL import Image
except ImportError:
    sys.exit("Pillow required: pip install pillow")

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
_ROOT       = os.path.dirname(_SCRIPT_DIR)
_GRAPHX     = os.path.join(_ROOT, "GraphX")
_PNG        = os.path.join(_GRAPHX, "caisse.png")
_OUT_C      = os.path.join(_GRAPHX, "caisse_tiles.c")
_OUT_H      = os.path.join(_GRAPHX, "caisse_tiles.h")

# Palette : meme que hent_palettes[].
# C0 transparent, C1 marron fonce, C2 marron clair, C3 inutilise.
PAL_NGPC = [0x0000, 0x0135, 0x0269, 0x0000]

# Mapping RGB888 -> index palette.
# Couleurs du PNG : (0,0,0,0) transp / (0,0,0,255) noir / (81,55,20) marron fonce /
#                   (148,104,42) marron clair.
def _color_to_idx(rgba):
    r, g, b, a = rgba
    if a < 128:
        return 0  # transparent
    # noir = outline = C1 (proche du marron fonce)
    if r < 16 and g < 16 and b < 16:
        return 1
    # marron fonce
    if 70 <= r <= 95 and 45 <= g <= 65 and 12 <= b <= 28:
        return 1
    # marron clair
    if 130 <= r <= 165 and 90 <= g <= 115 and 30 <= b <= 55:
        return 2
    # fallback : nearest entre C1 et C2
    d1 = abs(r - 81) + abs(g - 55) + abs(b - 20)
    d2 = abs(r - 148) + abs(g - 104) + abs(b - 42)
    return 1 if d1 < d2 else 2


def _tile_to_words(tile_pixels):
    """tile_pixels = 64 indices (0..3), retourne 8 u16 NGPC.
    Pixel 0 (x=0) -> bits [15:14], pixel 7 (x=7) -> bits [1:0]."""
    words = []
    for row in range(8):
        w = 0
        for col in range(8):
            idx = tile_pixels[row * 8 + col]
            shift = (7 - col) * 2
            w |= (idx & 0x3) << shift
        words.append(w)
    return words


def main():
    if not os.path.isfile(_PNG):
        sys.exit("ERROR: %s not found" % _PNG)
    im = Image.open(_PNG).convert("RGBA")
    w, h = im.size
    if (w, h) != (16, 16):
        sys.exit("ERROR: caisse.png is %dx%d, expected 16x16" % (w, h))

    # Decoupe en 4 sous-tiles 8x8 (TL, TR, BL, BR).
    tile_words = []
    for sy in (0, 8):
        for sx in (0, 8):
            pixels = []
            for y in range(8):
                for x in range(8):
                    pixels.append(_color_to_idx(im.getpixel((sx + x, sy + y))))
            tile_words.extend(_tile_to_words(pixels))

    # Emit .h
    with open(_OUT_H, "w") as f:
        f.write("/* Generated by tools/export_caisse.py - do not edit */\n")
        f.write("#ifndef CAISSE_TILES_H\n")
        f.write("#define CAISSE_TILES_H\n\n")
        f.write('#include "ngpc_types.h"\n\n')
        f.write("/* 4 tiles NGPC 2bpp (TL TR BL BR) = 32 u16. */\n")
        f.write("extern const u16 NGP_FAR caisse_tiles[32];\n\n")
        f.write("/* Palette 4 couleurs : C0 transp, C1 marron fonce, C2 marron clair, C3 unused.\n")
        f.write(" * Identique a hent_palettes (a charger une seule fois en SCR2 slot dedie). */\n")
        f.write("extern const u16 NGP_FAR caisse_palette[4];\n\n")
        f.write("#endif /* CAISSE_TILES_H */\n")

    # Emit .c
    with open(_OUT_C, "w") as f:
        f.write("/* Generated by tools/export_caisse.py - do not edit */\n")
        f.write('#include "caisse_tiles.h"\n\n')
        f.write("const u16 NGP_FAR caisse_tiles[32] = {\n")
        for ti in range(4):
            f.write("    /* tile %d */ " % ti)
            chunk = tile_words[ti * 8:(ti + 1) * 8]
            f.write(", ".join("0x%04X" % w for w in chunk))
            f.write(",\n")
        f.write("};\n\n")
        f.write("const u16 NGP_FAR caisse_palette[4] = {\n    ")
        f.write(", ".join("0x%04X" % c for c in PAL_NGPC))
        f.write("\n};\n")

    print("Wrote %s and %s" % (_OUT_H, _OUT_C))


if __name__ == "__main__":
    main()
