"""
ngpc_palette_viewer.py - Extract NGPC sprite palettes and export for Aseprite

Reads all *_mspr.c files in a GraphX/ folder and produces:
  ngpc_palettes.gpl   -> load directly in Aseprite: Edit > Palettes > Load Palette
  ngpc_palettes.png   -> visual swatch, one row per palette slot (4 cols x 16 rows)
  ngpc_palettes.txt   -> text report: slot / sprite / hex / rgb

Usage:
    python tools/ngpc_palette_viewer.py [GraphX_dir] [--out out_dir]

    # From project root (default: reads GraphX/, writes next to it):
    python tools/ngpc_palette_viewer.py

    # Explicit paths:
    python tools/ngpc_palette_viewer.py GraphX --out GraphX
"""
from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

try:
    from PIL import Image, ImageDraw
except ImportError:
    print("Error: Pillow is required.  pip install pillow", file=sys.stderr)
    raise SystemExit(2)

# ── NGPC constants ───────────────────────────────────────────────────────────

MAX_SLOTS   = 16   # NGPC hardware: 16 sprite palette slots (0..15)
COLORS_PER  = 4    # 4 colors per slot (index 0 = transparent)

# ── visual config ─────────────────────────────────────────────────────────────

CELL_W    = 28     # pixels per color swatch cell
CELL_H    = 28
LABEL_W   = 220    # right-side label column width
BORDER    = 1      # 1-px border between cells
BG_COLOR  = (20, 20, 20)
GRID_CLR  = (55, 55, 55)
UNUSED_BG = (12, 12, 12)
TEXT_USED = (200, 200, 200)
TEXT_FREE = (65,  65,  65)
CHECKER_A = (38,  38,  38)   # transparency checkerboard A
CHECKER_B = (22,  22,  22)   #                           B

# ── color conversion ──────────────────────────────────────────────────────────

def rgb444_to_rgb888(v: int) -> tuple[int, int, int]:
    """
    NGPC RGB444 storage format: 0x0BGR  (u16 word)
      bits  3-0  = R nibble
      bits  7-4  = G nibble
      bits 11-8  = B nibble
    Expand each nibble to 8 bits by shifting left 4.
    """
    r = (v & 0x00F) << 4
    g = ((v >> 4) & 0xF) << 4
    b = ((v >> 8) & 0xF) << 4
    return (r, g, b)

def rgb888_to_gpl(rgb: tuple[int, int, int], label: str) -> str:
    return f"{rgb[0]:3d} {rgb[1]:3d} {rgb[2]:3d}\t{label}"

# ── data model ────────────────────────────────────────────────────────────────

@dataclass
class PaletteSlot:
    slot:        int
    sprite_name: str               # primary sprite name (or "name1 + name2 + ..." if shared)
    raw_colors:  list[int] = field(default_factory=list)   # 4 RGB444 values
    shared:      bool = False      # True if multiple sprites share this slot

    def rgb888(self, idx: int) -> tuple[int, int, int] | None:
        """Return RGB888 for color index, or None if transparent (index 0)."""
        if idx == 0:
            return None   # always transparent
        v = self.raw_colors[idx] if idx < len(self.raw_colors) else 0
        return rgb444_to_rgb888(v)   # 0x0000 = pure black (not transparent here)

    def is_empty(self) -> bool:
        """True if all non-transparent colors are 0 (slot is blank/padding)."""
        return all(self.raw_colors[i] == 0 for i in range(1, COLORS_PER))

# ── mspr.c parser ─────────────────────────────────────────────────────────────

def parse_mspr_c(path: Path) -> list[PaletteSlot]:
    """
    Parse a *_mspr.c file generated by ngpc_sprite_export.py.

    Extracts:
      {name}_pal_base       -> first palette slot used
      {name}_palette_count  -> how many consecutive slots
      {name}_palettes[]     -> flat array of RGB444 u16 values (pal_count * 4 entries)

    Returns one PaletteSlot per slot claimed by this sprite file.
    """
    text = path.read_text(encoding="utf-8", errors="replace")

    # Derive a human-readable sprite name from the filename
    stem = path.stem  # e.g. "shmup_player_a_mspr"
    sprite_name = stem[:-5] if stem.endswith("_mspr") else stem

    m = re.search(r"_pal_base\s*=\s*(\d+)", text)
    pal_base = int(m.group(1)) if m else 0

    m = re.search(r"_palette_count\s*=\s*(\d+)", text)
    pal_count = int(m.group(1)) if m else 1

    m = re.search(r"_palettes\[\]\s*=\s*\{([^}]+)\}", text, re.DOTALL)
    raw: list[int] = []
    if m:
        raw = [int(v, 16) for v in re.findall(r"0x([0-9A-Fa-f]{4})", m.group(1))]

    # Pad to expected length
    expected = pal_count * COLORS_PER
    while len(raw) < expected:
        raw.append(0)

    slots: list[PaletteSlot] = []
    for i in range(pal_count):
        slot_idx = pal_base + i
        if slot_idx >= MAX_SLOTS:
            print(f"  Warning: {sprite_name} slot {slot_idx} >= {MAX_SLOTS}, skipped.", file=sys.stderr)
            continue
        colors = raw[i * COLORS_PER : (i + 1) * COLORS_PER]
        while len(colors) < COLORS_PER:
            colors.append(0)
        slots.append(PaletteSlot(slot=slot_idx, sprite_name=sprite_name, raw_colors=colors))

    return slots


def collect_all_slots(graphx_dir: Path) -> list[PaletteSlot | None]:
    """
    Scan all *_mspr.c files and return a list of 16 entries (one per slot).
    Entry is None if the slot is unclaimed.
    """
    slots: list[PaletteSlot | None] = [None] * MAX_SLOTS

    for path in sorted(graphx_dir.glob("*_mspr.c")):
        try:
            parsed = parse_mspr_c(path)
        except Exception as exc:
            print(f"  Warning: could not parse {path.name}: {exc}", file=sys.stderr)
            continue

        for ps in parsed:
            existing = slots[ps.slot]
            if existing is not None:
                # Intentional palette sharing: merge sprite names, keep colors from first.
                existing.sprite_name = existing.sprite_name + " + " + ps.sprite_name
                existing.shared = True
            else:
                slots[ps.slot] = ps

    return slots

# ── outputs ───────────────────────────────────────────────────────────────────

def write_gpl(slots: list[PaletteSlot | None], out_path: Path) -> None:
    """
    Write a GIMP Palette (.gpl) file.

    Aseprite import: Edit > Palettes > Load Palette (or drag .gpl onto palette panel)
    GIMP import:     Windows > Dockable Dialogs > Palettes > Import

    Layout: 5 columns per row (Columns: 5).
    Each row = 1 palette slot: [transparent][c1][c2][c3][SEPARATOR]
    The separator (bright magenta 255,0,255) is not a valid NGPC color
    (NGPC channels are multiples of 16 only) so it is easy to spot.
    Total entries: MAX_SLOTS * 5 = 80.
    """
    # Separator color: bright magenta — clearly not an NGPC RGB444 color.
    SEP_RGB   = (255, 0, 255)
    SEP_LABEL = "---"

    used_count = sum(1 for s in slots if s is not None)
    free_count = MAX_SLOTS - used_count

    lines = [
        "GIMP Palette",
        "Name: NGPC Sprites",
        "Columns: 5",
        "#",
        f"# NGPC sprite palettes — {used_count}/{MAX_SLOTS} slots used, {free_count} free",
        "# Layout: 5 cols per row = [transparent][c1][c2][c3][magenta separator]",
        "# Index 0 of each slot = TRANSPARENT (always black in GPL, do not paint with it)",
        "# Colors are RGB444 expanded to RGB888 (multiples of 16 per channel)",
        "# Magenta (255,0,255) = slot separator, NOT a game color",
        "#",
    ]

    for slot_idx, ps in enumerate(slots):
        if ps is not None:
            lines.append(f"# Slot {slot_idx:02d} — {ps.sprite_name}")
            # index 0: transparent
            lines.append(rgb888_to_gpl((0, 0, 0), f"s{slot_idx:02d}_transparent"))
            # indices 1-3: actual colors
            for i in range(1, COLORS_PER):
                rgb = ps.rgb888(i) or (0, 0, 0)
                v   = ps.raw_colors[i]
                lines.append(rgb888_to_gpl(rgb, f"s{slot_idx:02d}_c{i}_#{v:03X}"))
        else:
            lines.append(f"# Slot {slot_idx:02d} — (unused / free)")
            lines.append(rgb888_to_gpl((0, 0, 0), f"s{slot_idx:02d}_free_0"))
            for i in range(1, COLORS_PER):
                lines.append(rgb888_to_gpl((0, 0, 0), f"s{slot_idx:02d}_free_{i}"))

        # Separator at position 4 of each row
        lines.append(rgb888_to_gpl(SEP_RGB, SEP_LABEL))

    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _draw_checker(draw: ImageDraw.ImageDraw, x: int, y: int, size: int = 4) -> None:
    """Draw a transparency checkerboard pattern in a CELL_W x CELL_H area."""
    for cy in range(0, CELL_H, size):
        for cx in range(0, CELL_W, size):
            color = CHECKER_A if ((cx // size + cy // size) % 2 == 0) else CHECKER_B
            draw.rectangle(
                [x + cx, y + cy, x + cx + size - 1, y + cy + size - 1],
                fill=color,
            )


def write_png(slots: list[PaletteSlot | None], out_path: Path) -> None:
    """
    Write a visual palette swatch PNG.

    Layout: 16 rows (one per slot) x 4 columns (one per color).
    Column 0 always shows a checkerboard (transparent).
    A label with slot number and sprite name is shown on the right.

    To use in Aseprite: open the PNG, then use Edit > Palettes > Load from Sprite.
    Or just reference it visually when drawing sprites.
    """
    row_h  = CELL_H + BORDER
    img_w  = COLORS_PER * (CELL_W + BORDER) + LABEL_W
    img_h  = MAX_SLOTS * row_h + BORDER

    img  = Image.new("RGB", (img_w, img_h), BG_COLOR)
    draw = ImageDraw.Draw(img)

    used_count = sum(1 for s in slots if s is not None)

    for slot_idx, ps in enumerate(slots):
        row_y = BORDER + slot_idx * row_h

        # Draw separator line above each row
        draw.line([(0, row_y - BORDER), (img_w, row_y - BORDER)], fill=GRID_CLR)

        for col in range(COLORS_PER):
            cell_x = BORDER + col * (CELL_W + BORDER)

            if col == 0:
                # Always checkerboard for transparent index
                _draw_checker(draw, cell_x, row_y)
                draw.rectangle(
                    [cell_x, row_y, cell_x + CELL_W - 1, row_y + CELL_H - 1],
                    outline=GRID_CLR,
                )
            elif ps is not None:
                rgb = ps.rgb888(col) or (0, 0, 0)
                draw.rectangle(
                    [cell_x, row_y, cell_x + CELL_W - 1, row_y + CELL_H - 1],
                    fill=rgb,
                    outline=GRID_CLR,
                )
                # Show hex value inside cell if it fits
                v = ps.raw_colors[col]
                hex_lbl = f"#{v:03X}"
                # brightness → pick text color
                br = 0.299 * rgb[0] + 0.587 * rgb[1] + 0.114 * rgb[2]
                txt_clr = (0, 0, 0) if br > 100 else (180, 180, 180)
                draw.text((cell_x + 2, row_y + CELL_H - 10), hex_lbl, fill=txt_clr)
            else:
                # Unused slot
                draw.rectangle(
                    [cell_x, row_y, cell_x + CELL_W - 1, row_y + CELL_H - 1],
                    fill=UNUSED_BG,
                    outline=GRID_CLR,
                )

        # Label (right of the 4 cells)
        label_x = BORDER + COLORS_PER * (CELL_W + BORDER) + 4
        label_y = row_y + CELL_H // 2 - 4

        if ps is not None:
            prefix = f"{slot_idx:02d}  "
            suffix = f"[shared] {ps.sprite_name}" if ps.shared else ps.sprite_name
            draw.text((label_x, label_y), prefix + suffix, fill=TEXT_USED)
        else:
            draw.text((label_x, label_y), f"{slot_idx:02d}  (free)", fill=TEXT_FREE)

    # Summary footer line
    draw.line([(0, img_h - 1), (img_w, img_h - 1)], fill=GRID_CLR)

    # Scale up x2 for readability
    img = img.resize((img_w * 2, img_h * 2), Image.NEAREST)
    img.save(out_path)


def write_txt(slots: list[PaletteSlot | None], out_path: Path) -> None:
    """Write a plain-text palette report."""
    used = [s for s in slots if s is not None]
    free = [i for i, s in enumerate(slots) if s is None]

    lines = [
        "NGPC Palette Report",
        "=" * 60,
        f"Used: {len(used)}/{MAX_SLOTS} palette slots",
        f"Free: {len(free)} slot(s) — indices: {free if free else 'none'}",
        "",
    ]

    for slot_idx, ps in enumerate(slots):
        if ps is None:
            lines.append(f"Slot {slot_idx:02d}  (unused)")
            lines.append("")
            continue

        lines.append(f"Slot {slot_idx:02d}  {ps.sprite_name}")
        for i in range(COLORS_PER):
            if i == 0:
                lines.append(f"        [0] transparent")
            else:
                v   = ps.raw_colors[i]
                rgb = rgb444_to_rgb888(v)
                lines.append(f"        [{i}] #{v:03X}  ->  rgb({rgb[0]}, {rgb[1]}, {rgb[2]})")
        lines.append("")

    if free:
        lines += [
            "─" * 60,
            "Tip: to share a palette between two sprites, make sure",
            "they use the exact same 3 opaque colors (RGB444-quantized).",
            "The exporter will reuse existing slots automatically.",
        ]

    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

# ── main ──────────────────────────────────────────────────────────────────────

def main() -> int:
    ap = argparse.ArgumentParser(
        description="Extract NGPC sprite palettes from *_mspr.c files and export for Aseprite"
    )
    ap.add_argument(
        "graphx_dir",
        nargs="?",
        default="GraphX",
        help="Path to GraphX/ folder containing *_mspr.c files (default: GraphX)",
    )
    ap.add_argument(
        "--out",
        default=None,
        help="Output directory for generated files (default: same as graphx_dir)",
    )
    args = ap.parse_args()

    graphx_dir = Path(args.graphx_dir).resolve()
    out_dir    = Path(args.out).resolve() if args.out else graphx_dir

    if not graphx_dir.exists():
        print(f"Error: folder not found: {graphx_dir}", file=sys.stderr)
        return 2

    mspr_files = list(graphx_dir.glob("*_mspr.c"))
    if not mspr_files:
        print(f"No *_mspr.c files found in {graphx_dir}", file=sys.stderr)
        print("Run the sprite export scripts first.", file=sys.stderr)
        return 1

    print(f"Scanning {len(mspr_files)} *_mspr.c files in: {graphx_dir}")
    slots = collect_all_slots(graphx_dir)

    used  = [s for s in slots if s is not None]
    free  = [i for i, s in enumerate(slots) if s is None]
    print(f"Palette slots: {len(used)}/{MAX_SLOTS} used, {len(free)} free"
          + (f" [{free}]" if free else " [none]"))

    out_dir.mkdir(parents=True, exist_ok=True)

    gpl_path = out_dir / "ngpc_palettes.gpl"
    png_path = out_dir / "ngpc_palettes.png"
    txt_path = out_dir / "ngpc_palettes.txt"

    write_gpl(slots, gpl_path)
    print(f"Written: {gpl_path}")

    write_png(slots, png_path)
    print(f"Written: {png_path}")

    write_txt(slots, txt_path)
    print(f"Written: {txt_path}")

    print()
    print("-- Aseprite integration ----------------------------------")
    print("  Edit > Palettes > Load Palette > select ngpc_palettes.gpl")
    print("  (or drag .gpl onto the Aseprite palette panel)")
    print("----------------------------------------------------------")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
