/* Generated by gen_static_room_bank.py - do not edit */

#ifndef STATIC_ROOM_BANK_H
#define STATIC_ROOM_BANK_H

#include "ngpc_types.h"

#define STATIC_ROOM_BANK_COUNT 38u
#define STATIC_ROOM_BANK_MIN_W 10u
#define STATIC_ROOM_BANK_MIN_H 9u
#define STATIC_ROOM_BANK_MAX_W 14u
#define STATIC_ROOM_BANK_MAX_H 14u
#define STATIC_ROOM_BANK_MAX_MASK_VARIANTS 4u
#define STATIC_ROOM_BANK_INVALID_INDEX 255u
#define STATIC_ROOM_MAX_DECOR_ANCHORS 12u  /* MKD-3-A */

#define STATIC_ROOM_EXIT_N 0x01u
#define STATIC_ROOM_EXIT_E 0x02u
#define STATIC_ROOM_EXIT_S 0x04u
#define STATIC_ROOM_EXIT_W 0x08u

#define STATIC_ROOM_ROLE_NODE 0u
#define STATIC_ROOM_ROLE_LEAF 1u

#define STATIC_ROOM_FEATURE_INNER         0x01u
#define STATIC_ROOM_FEATURE_VOID          0x02u
#define STATIC_ROOM_FEATURE_DECOR         0x04u
#define STATIC_ROOM_FEATURE_STAIR_SOCKET  0x08u
#define STATIC_ROOM_FEATURE_ENEMY_SPAWNS  0x10u
#define STATIC_ROOM_FEATURE_ITEM_SPAWNS   0x20u
#define STATIC_ROOM_FEATURE_ENTRY_UNIQUE  0x40u  /* MKD-7 : prefer for slot 0 */

/* MKD-6 : roles semantiques (drive furnishing MKD-3). Stables, ne pas
 * reordonner (le cluster_generate et le furnishing les hashent par valeur). */
#define STATIC_ROOM_SEMANTIC_ENTRY         0u
#define STATIC_ROOM_SEMANTIC_TRANSIT       1u
#define STATIC_ROOM_SEMANTIC_COMBAT_LIGHT  2u
#define STATIC_ROOM_SEMANTIC_COMBAT_HEAVY  3u
#define STATIC_ROOM_SEMANTIC_TREASURE      4u
#define STATIC_ROOM_SEMANTIC_SAFE          5u
#define STATIC_ROOM_SEMANTIC_STAIR         6u
#define STATIC_ROOM_SEMANTIC_SECRET        7u

typedef enum {
    STATIC_ROOM_CELL_FLOOR = 0,
    STATIC_ROOM_CELL_CRACK,
    STATIC_ROOM_CELL_OUTER_WALL,
    STATIC_ROOM_CELL_INNER_WALL,
    STATIC_ROOM_CELL_VOID_DROP,
    STATIC_ROOM_CELL_PILLAR,
    STATIC_ROOM_CELL_DECO_TOTEM,
    STATIC_ROOM_CELL_DECO_VASE
} StaticRoomCell;

typedef struct {
    u8 x;
    u8 y;
} StaticRoomPoint;

typedef struct {
    const char *name;
    u8 w;
    u8 h;
    u8 exits_mask;
    u8 role;
    u8 feature_flags;
    u8 semantic_role;        /* MKD-6 : STATIC_ROOM_SEMANTIC_* */
    u8 door_col_lo;
    u8 door_col_hi;
    u8 door_row_lo;
    u8 door_row_hi;
    u8 enemy_spawn_count;
    u8 item_spawn_count;
    u8 stair_socket_count;
    u8 decor_anchor_count;   /* MKD-3-A : nombre d'anchors decor (runtime decide) */
    const u8 *cells;
    const StaticRoomPoint *enemy_spawns;
    const StaticRoomPoint *item_spawns;
    const StaticRoomPoint *stair_sockets;
    const StaticRoomPoint *decor_anchors;  /* MKD-3-A */
} StaticRoomDef;

const StaticRoomDef *static_room_bank_get(u8 room_idx);
u8 static_room_bank_count_for_mask(u8 exits_mask);
u8 static_room_bank_index_for_mask(u8 exits_mask, u8 variant_idx);

#endif /* STATIC_ROOM_BANK_H */
